#deseqR

In [ ]:
# STEP 1
install.packages("BiocManager")

# STEP 2
options(repos = BiocManager::repositories())

# STEP 3
BiocManager::install(c(
  "DelayedArray",
  "SummarizedExperiment",
  "BiocParallel",
  "DESeq2"
), ask = FALSE, update = FALSE)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com

'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    BioCsoft: https://bioconductor.org/packages/3.23/bioc
    BioCann: https://bioconductor.org/packages/3.23/data/annotation
    BioCexp: https://bioconductor.org/packages/3.23/data/experiment
    BioCworkflows: https://bioconductor.org/packages/3.23/workflows
    BioCbooks: https://bioconductor.org/packages/3.23/books
    CRAN: https://cran.rstudio.com

Bioconductor version 3.23 (BiocManager 1.30.27), R 4.6.0 (2026-04-24)

Installing package(s) 'BiocVersion', 'DelayedArray', 'SummarizedExperiment',
  'BiocParallel', 'DESeq2'

also installing the dependencies ‘formatR’, ‘abind’, ‘XVector’, ‘lambda.r’, ‘futile.options’, ‘BiocGenerics’, ‘MatrixGenerics’, ‘S4Vectors’, ‘IRanges’, ‘S4Arrays’, ‘SparseArray’, ‘GenomicRanges’, ‘Biobase’, ‘Seqinfo’, ‘futile.logger’, ‘snow’, ‘BH’, ‘matrixStats’, ‘locfit’, ‘RcppArmadillo’

In [ ]:
library(DESeq2)

# load data
counts <- read.csv("/content/gse108966_esp_counts.csv", row.names=1)
labels <- read.csv("/content/gse108966_esp_labels.csv")

# transpose counts
counts <- t(counts)

In [ ]:
# create metadata
coldata <- data.frame(
    condition = as.factor(labels$condition)
)

# build DESeq dataset
dds <- DESeqDataSetFromMatrix(
    countData = counts,
    colData = coldata,
    design = ~ condition
)

# run DESeq2
dds <- DESeq(dds)

# get results
res <- results(dds)

# sort by adjusted p-value
resOrdered <- res[order(res$padj), ]

# save results
write.csv(as.data.frame(resOrdered),
          "est_DESeq2_results.csv")

estimating size factors

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

final dispersion estimates

fitting model and testing

-- replacing outliers and refitting for 4 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

estimating dispersions

fitting model and testing

In [ ]:
print(resOrdered)

log2 fold change (MLE): condition 1 vs 0
Wald test p-value: condition 1 vs 0
DataFrame with 2588 rows and 6 columns
                 baseMean log2FoldChange     lfcSE      stat      pvalue
                <numeric>      <numeric> <numeric> <numeric>   <numeric>
hsa.miR.4485.3p 262.39542        6.36713  0.535257  11.89546 1.24966e-32
hsa.miR.5701     83.14801        1.79616  0.220865   8.13237 4.20994e-16
hsa.miR.5585.3p  24.48987        3.44923  0.437013   7.89273 2.95643e-15
hsa.miR.4484      3.45389        3.35862  0.442776   7.58538 3.31511e-14
hsa.miR.4284      5.94010        4.81325  0.655746   7.34012 2.13406e-13
...                   ...            ...       ...       ...         ...
hsa.miR.936     0.0000000             NA        NA        NA          NA
hsa.miR.937.5p  0.0910623      -0.170161  0.978919 -0.173825    0.862003
hsa.miR.938     0.0000000             NA        NA        NA          NA
hsa.miR.9500    0.0000000             NA        NA        NA          NA
hsa.miR.96.3p   0.1852750       0.349810  0.709529  0.493017    0.622000
                       padj
                  <numeric>
hsa.miR.4485.3p 1.66580e-29
hsa.miR.5701    2.80592e-13
hsa.miR.5585.3p 1.31364e-12
hsa.miR.4484    1.10476e-11
hsa.miR.4284    5.68941e-11
...                     ...
hsa.miR.936              NA
hsa.miR.937.5p           NA
hsa.miR.938              NA
hsa.miR.9500             NA
hsa.miR.96.3p            NA

In [ ]:
significant <- subset(resOrdered,
                      padj < 0.05 &
                      abs(log2FoldChange) > 1)

In [ ]:
head(significant)

log2 fold change (MLE): condition 1 vs 0
Wald test p-value: condition 1 vs 0
DataFrame with 6 rows and 6 columns
                 baseMean log2FoldChange     lfcSE      stat      pvalue
                <numeric>      <numeric> <numeric> <numeric>   <numeric>
hsa.miR.4485.3p 262.39542        6.36713  0.535257  11.89546 1.24966e-32
hsa.miR.5701     83.14801        1.79616  0.220865   8.13237 4.20994e-16
hsa.miR.5585.3p  24.48987        3.44923  0.437013   7.89273 2.95643e-15
hsa.miR.4484      3.45389        3.35862  0.442776   7.58538 3.31511e-14
hsa.miR.4284      5.94010        4.81325  0.655746   7.34012 2.13406e-13
hsa.miR.3607.3p  43.61768        1.51354  0.225559   6.71017 1.94397e-11
                       padj
                  <numeric>
hsa.miR.4485.3p 1.66580e-29
hsa.miR.5701    2.80592e-13
hsa.miR.5585.3p 1.31364e-12
hsa.miR.4484    1.10476e-11
hsa.miR.4284    5.68941e-11
hsa.miR.3607.3p 3.70188e-09

In [ ]:
write.csv(as.data.frame(significant),
          "significant_deseq2_results.csv")

# EDGER

In [ ]:
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}
BiocManager::install("edgeR", update = FALSE, ask = FALSE)

library(edgeR)

# Load data for edgeR
edger_counts <- read.csv("/content/gse108966_esp_counts.csv", row.names=1)
edger_labels <- read.csv("/content/gse108966_esp_labels.csv")

# Transpose counts if necessary (edgeR expects genes as rows, samples as columns)
# Assuming the loaded counts are already in the correct orientation (genes as rows, samples as columns).
# If not, you might need to transpose: edger_counts <- t(edger_counts)
# For now, we will proceed assuming the files are structured correctly for edgeR.

'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    BioCsoft: https://bioconductor.org/packages/3.23/bioc
    BioCann: https://bioconductor.org/packages/3.23/data/annotation
    BioCexp: https://bioconductor.org/packages/3.23/data/experiment
    BioCworkflows: https://bioconductor.org/packages/3.23/workflows
    BioCbooks: https://bioconductor.org/packages/3.23/books
    CRAN: https://cran.rstudio.com

Bioconductor version 3.23 (BiocManager 1.30.27), R 4.6.0 (2026-04-24)

Warning message:
“package(s) not installed when version(s) same as or greater than current; use
  `force = TRUE` to re-install: 'edgeR'”

In [ ]:
library(edgeR)

# Convert to matrix
counts <- as.matrix(edger_counts)

# Replace NA
counts[is.na(counts)] <- 0

# IMPORTANT:
# transpose because edgeR expects:
# rows = genes/miRNAs
# cols = samples

counts <- t(counts)

# Ensure numeric
mode(counts) <- "numeric"

# Ensure integer counts
counts <- round(counts)

# Check dimensions
dim(counts)

# Create DGEList
dge <- DGEList(counts = counts)

# Labels
condition <- factor(edger_labels$condition)

# Check matching
length(condition)
ncol(dge)

# Must match
stopifnot(length(condition) == ncol(dge))

# Design matrix
design <- model.matrix(~condition)

# Filter low-expression miRNAs
keep <- filterByExpr(dge, design)

dge <- dge[keep,,keep.lib.sizes=FALSE]

# Normalize
dge <- calcNormFactors(dge)

# Estimate dispersion
dge <- estimateDisp(dge, design)

# Fit model
fit <- glmFit(dge, design)

# Differential expression
lrt <- glmLRT(fit)

# Results
results <- topTags(lrt, n=Inf)

# View
head(results$table)

[1] 2588   91

[1] 91

[1] 91

calcNormFactors has been renamed to normLibSizes

                logFC     logCPM   LR        PValue       FDR
hsa.miR.4485.3p 6.3969290 5.472444 128.73738 7.741236e-30 5.325970e-27
hsa.miR.5585.3p 3.4456177 2.129981  66.80062 3.004041e-16 1.033390e-13
hsa.miR.5701    1.7592309 3.799238  65.76935 5.069055e-16 1.162503e-13
hsa.miR.3607.3p 1.4753729 2.886919  45.22190 1.759265e-11 3.025936e-09
hsa.miR.4532    3.2006545 2.653661  35.47712 2.580642e-09 3.550964e-07
hsa.let.7f.2.3p 0.9036379 4.999815  34.90873 3.455283e-09 3.962058e-07

In [ ]:
edgeR_results <- results$table

sig_mirnas <- edgeR_results[
    edgeR_results$FDR < 0.05 &
    abs(edgeR_results$logFC) > 1,
]

head(sig_mirnas)

                logFC    logCPM    LR        PValue       FDR
hsa.miR.4485.3p 6.396929  5.472444 128.73738 7.741236e-30 5.325970e-27
hsa.miR.5585.3p 3.445618  2.129981  66.80062 3.004041e-16 1.033390e-13
hsa.miR.5701    1.759231  3.799238  65.76935 5.069055e-16 1.162503e-13
hsa.miR.3607.3p 1.475373  2.886919  45.22190 1.759265e-11 3.025936e-09
hsa.miR.4532    3.200654  2.653661  35.47712 2.580642e-09 3.550964e-07
hsa.miR.21.3p   1.150086 11.459435  25.78618 3.814101e-07 2.915669e-05

COMMON

In [ ]:
# Get significant miRNA names from DESeq2 results
deseq2_sig_mirnas <- rownames(significant)

# Get significant miRNA names from edgeR results
edger_sig_mirnas <- rownames(sig_mirnas)

# Find the common miRNAs
common_mirnas <- intersect(deseq2_sig_mirnas, edger_sig_mirnas)

# Print the common miRNAs and their count
print(paste("Number of common significant miRNAs:", length(common_mirnas)))
if (length(common_mirnas) > 0) {
  print("Common significant miRNAs:")
  print(common_mirnas)
} else {
  print("No common significant miRNAs found between DESeq2 and edgeR at the specified thresholds.")
}

[1] "Number of common significant miRNAs: 25"
[1] "Common significant miRNAs:"
 [1] "hsa.miR.4485.3p"  "hsa.miR.5701"     "hsa.miR.5585.3p"  "hsa.miR.3607.3p"
 [5] "hsa.miR.4532"     "hsa.miR.21.3p"    "hsa.miR.3613.5p"  "hsa.miR.378e"
 [9] "hsa.miR.7641"     "hsa.miR.9.3p"     "hsa.miR.378d"     "hsa.miR.589.3p"
[13] "hsa.miR.619.5p"   "hsa.miR.4461"     "hsa.miR.1273g.3p" "hsa.miR.9.5p"
[17] "hsa.miR.136.5p"   "hsa.miR.362.3p"   "hsa.miR.1249.3p"  "hsa.miR.766.3p"
[21] "hsa.miR.124.3p"   "hsa.miR.412.5p"   "hsa.miR.5010.5p"  "hsa.miR.135a.3p"
[25] "hsa.miR.423.5p"

In [ ]:
prev1 = read.csv("/content/all_top10_consensus_RIFgse108966_Biomarkers.csv")

In [ ]:
# Re-read prev1 to ensure it's available and correctly parsed
# Assuming the miRNA names are in the first column of the CSV
prev1_data <- read.csv("/content/all_top10_consensus_RIFgse108966_Biomarkers.csv")
prev_mirnas <- as.character(prev1_data[[1]])

# Find the common miRNAs between common_mirnas and prev_mirnas
common_to_all <- intersect(common_mirnas, prev_mirnas)

# Print the results
print(paste("Number of common miRNAs in DESeq2, edgeR, and prev dataset:", length(common_to_all)))
if (length(common_to_all) > 0) {
  print("Common miRNAs across all datasets:")
  print(common_to_all)
} else {
  print("No common miRNAs found across DESeq2, edgeR, and the prev dataset.")
}

[1] "Number of common miRNAs in DESeq2, edgeR, and prev dataset: 0"
[1] "No common miRNAs found across DESeq2, edgeR, and the prev dataset."