# genes linked to the miRNA
using mirdb and target scan
miRNA


1.  hsa-miR-5701 PABPC5, LAPTM4A
2.  hsa-miR-3607-3p	VPS13A, GMFB, FMO2, UBXN2B, PDE4D, FRG1, FAM65A, ARSJ, CLOCK, KCNIP4, DBF4, QPCT, KRTAP4-6, ACTL7B, KCNJ6, HOMER1, HAUS1, TPO, HIATL1, IGFBP7, TRIQK, ELP4, AC008964.1, IL6ST, ORMDL1, C16orf74, LPPR1, AC144568.2, ZNF175, RAB6C, LINC00923, RP11-160N1.1, PI4K2B, GAS6, FAM169A, CPNE4, CHRAC1, MOSPD1, BTF3L4, HOXA2, YEATS4, RP11-321M21.3, MANEA, ZNF654, SLC15A4, ZNF684, SP4, DFNA5, RAB7A, CHN1, AMACR, PIH1D3, RGS17, DPP8, TUSC3, PSTPIP2, ENPP5, P2RY10, TAF12, DCTN6, VIM, H1F0, PDIA4, FAM103A1, RPL31, BCKDHB, MLN, ZMYM2, SLC44A3, RAB6A, PAGE5, MOB4, MFSD2A, MRPL19, PKHD1, LYZ, RASSF8, RUFY1, TMEM217, NR2F2, HMG20A, AP000889.3, FZD3, TFB1M, CHTF18, FAM122B, ANAPC13, CHRNA6, GAGE12B, GCFC2, IKZF2, MMD, ZNF711, MAML2, FJX1, DCAF6, AC024257.1, KRT10, TMEM57, BTBD7, PIGF, L1TD1, ZW10, HEXIM2, TYW5, TVP23B, AL359195.1, UNC93B1, PEG3, ZNF677, SCAF11, CHIC1, MRPS18C, CCDC158, CTHRC1, RP6-24A23.6, CUL7, PLA1A, MPZL3, HSPE1-MOB4, KIAA0087, SCOC, KDM3A, REV1, HIST1H3G, CLDN10

In [107]:
import gseapy
import pandas as pd

# Gene lists provided by the user
genes_mir5701 = ["PABPC5", "LAPTM4A"]
genes_mir3607_3p = [
    "VPS13A", "GMFB", "FMO2", "UBXN2B", "PDE4D", "FRG1", "FAM65A", "ARSJ", "CLOCK",
    "KCNIP4", "DBF4", "QPCT", "KRTAP4-6", "ACTL7B", "KCNJ6", "HOMER1", "HAUS1",
    "TPO", "HIATL1", "IGFBP7", "TRIQK", "ELP4", "AC008964.1", "IL6ST", "ORMDL1",
    "C16orf74", "LPPR1", "AC144568.2", "ZNF175", "RAB6C", "LINC00923", "RP11-160N1.1",
    "PI4K2B", "GAS6", "FAM169A", "CPNE4", "CHRAC1", "MOSPD1", "BTF3L4", "HOXA2",
    "YEATS4", "RP11-321M21.3", "MANEA", "ZNF654", "SLC15A4", "ZNF684", "SP4",
    "DFNA5", "RAB7A", "CHN1", "AMACR", "PIH1D3", "RGS17", "DPP8", "TUSC3",
    "PSTPIP2", "ENPP5", "P2RY10", "TAF12", "DCTN6", "VIM", "H1F0", "PDIA4",
    "FAM103A1", "RPL31", "BCKDHB", "MLN", "ZMYM2", "SLC44A3", "RAB6A", "PAGE5",
    "MOB4", "MFSD2A", "MRPL19", "PKHD1", "LYZ", "RASSF8", "RUFY1", "TMEM217",
    "NR2F2", "HMG20A", "AP000889.3", "FZD3", "TFB1M", "CHTF18", "FAM122B",
    "ANAPC13", "CHRNA6", "GAGE12B", "GCFC2", "IKZF2", "MMD", "ZNF711", "MAML2",
    "FJX1", "DCAF6", "AC024257.1", "KRT10", "TMEM57", "BTBD7", "PIGF", "L1TD1",
    "ZW10", "HEXIM2", "TYW5", "TVP23B", "AL359195.1", "UNC93B1", "PEG3",
    "ZNF677", "SCAF11", "CHIC1", "MRPS18C", "CCDC158", "CTHRC1", "RP6-24A23.6",
    "CUL7", "PLA1A", "MPZL3", "HSPE1-MOB4", "KIAA0087", "SCOC", "KDM3A",
    "REV1", "HIST1H3G", "CLDN10"
]

# Combine and get unique genes
all_target_genes = list(set(genes_mir5701 + genes_mir3607_3p))
print(f"Total unique target genes: {len(all_target_genes)}")

# Perform KEGG enrichment analysis
enrichr_results = gseapy.enrichr(
    gene_list=all_target_genes,
    gene_sets='KEGG_2021_Human',
    organism='human', # Changed 'Human' to 'human'
    outdir=None, # no output directory for interactive use
    no_plot=True
)

# Display top KEGG pathways
print("\nTop 10 KEGG Enrichment Results:")
display(enrichr_results.results.head(10))

Total unique target genes: 128

Top 10 KEGG Enrichment Results:

,Gene_set,Term,Overlap,P-value,Adjusted P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes
0,KEGG_2021_Human,Ribosome,3/158,0.081046,0.812126,0,0,3.052955,7.671260,RPL31;MRPL19;MRPS18C
1,KEGG_2021_Human,Thyroid hormone synthesis,2/75,0.083408,0.812126,0,0,4.305066,10.693853,TPO;PDIA4
2,KEGG_2021_Human,Primary bile acid biosynthesis,1/17,0.103443,0.812126,0,0,9.771654,22.169313,AMACR
3,KEGG_2021_Human,Morphine addiction,2/91,0.115386,0.812126,0,0,3.528268,7.619205,KCNJ6;PDE4D
4,KEGG_2021_Human,Glycosylphosphatidylinositol (GPI)-anchor bios...,1/26,0.153833,0.812126,0,0,6.251024,11.701196,PIGF
5,KEGG_2021_Human,Cholinergic synapse,2/113,0.163310,0.812126,0,0,2.825826,5.120691,KCNJ6;CHRNA6
6,KEGG_2021_Human,Circadian rhythm,1/31,0.180603,0.812126,0,0,5.207874,8.913027,CLOCK
7,KEGG_2021_Human,Cell cycle,2/124,0.188429,0.812126,0,0,2.569607,4.288761,ANAPC13;DBF4
8,KEGG_2021_Human,Propanoate metabolism,1/34,0.196260,0.812126,0,0,4.733715,7.707975,BCKDHB
9,KEGG_2021_Human,Tyrosine metabolism,1/36,0.206533,0.812126,0,0,4.462767,7.039106,TPO

### Identify X-chromosome linked genes

To determine which of these target genes are located on the X chromosome, we can query a gene annotation database using the `mygene` library.

In [108]:
import mygene

mg = mygene.MyGeneInfo()

# Query for gene information, specifically chromosome location
gene_query_results = mg.querymany(
    all_target_genes,
    scopes='symbol', # Search by gene symbol
    fields='genomic_pos.chr',
    species='human',
    returnall=True, # Return all results, including unmatched
    as_dataframe=True
)

# Extract the 'out' DataFrame from the query results
gene_info_df = gene_query_results['out']

# Filter for genes located on the X chromosome
x_chromosome_genes = []

for gene_symbol in all_target_genes:
    # Check if the gene is in the query results DataFrame and has chromosome info
    if gene_symbol in gene_info_df.index:
        chr_data = gene_info_df.loc[gene_symbol, 'genomic_pos.chr']

        # Handle cases where chr_data might be a list or a single string
        if isinstance(chr_data, list):
            if 'X' in chr_data:
                x_chromosome_genes.append(gene_symbol)
        elif isinstance(chr_data, str):
            if chr_data == 'X':
                x_chromosome_genes.append(gene_symbol)


print(f"Total target genes: {len(all_target_genes)}")
print(f"Number of target genes on the X chromosome: {len(x_chromosome_genes)}")
print("Genes on the X chromosome:")
for gene in x_chromosome_genes:
    print(f"- {gene}")

1 input query terms found dup hits:	[('GAGE12B', 2)]
19 input query terms found no hit:	['FAM103A1', 'FAM122B', 'TMEM57', 'PIH1D3', 'LPPR1', 'RP11-160N1.1', 'AC024257.1', 'AL359195.1', 'AP

Total target genes: 128
Number of target genes on the X chromosome: 6
Genes on the X chromosome:
- PAGE5
- PABPC5
- MOSPD1
- CHIC1
- P2RY10
- ZNF711

In [110]:
import mygene
import pandas as pd

mg = mygene.MyGeneInfo()

# Genes to check
user_genes_to_check = ['PIH1D3', 'FAM122B', 'GAGE12B', 'RP6-24A2']

# Query for gene information, specifically chromosome location
query_results_specific = mg.querymany(
    user_genes_to_check,
    scopes='symbol',
    fields='genomic_pos.chr',
    species='human',
    returnall=True,
    as_dataframe=True
)

# Extract the 'out' DataFrame from the query results
specific_gene_info_df = query_results_specific['out']

print("Checking chromosomal location for specified genes:")
for gene_symbol in user_genes_to_check:
    if gene_symbol in specific_gene_info_df.index:
        chr_data_raw = specific_gene_info_df.loc[gene_symbol, 'genomic_pos.chr']

        # Normalize chr_data_raw into a list of unique, non-NA chromosome strings
        raw_values = []
        if isinstance(chr_data_raw, pd.Series):
            raw_values = chr_data_raw.dropna().tolist()
        elif isinstance(chr_data_raw, list):
            raw_values = [item for item in chr_data_raw if pd.notna(item)]
        elif pd.isna(chr_data_raw):
            raw_values = []
        else: # Must be a string or single value
            raw_values = [str(chr_data_raw)]

        chromosomes = list(set([str(c) for c in raw_values]))
        chromosomes.sort()

        if 'X' in chromosomes:
            print(f"- {gene_symbol}: Found on X chromosome.")
        elif len(chromosomes) > 0:
            print(f"- {gene_symbol}: Found on chromosomes {', '.join(chromosomes)} (not X).")
        else:
            print(f"- {gene_symbol}: Chromosome information not available.")
    else:
        print(f"- {gene_symbol}: Not found in MyGene.info database or no genomic position data.")

1 input query terms found dup hits:	[('GAGE12B', 2)]
3 input query terms found no hit:	['PIH1D3', 'FAM122B', 'RP6-24A2']

Checking chromosomal location for specified genes:
- PIH1D3: Chromosome information not available.
- FAM122B: Chromosome information not available.
- GAGE12B: Found on X chromosome.
- RP6-24A2: Chromosome information not available.

In [111]:
import gseapy

# Perform KEGG enrichment analysis for X-chromosome genes
x_kegg_enrichr_results = gseapy.enrichr(
    gene_list=x_chromosome_genes,
    gene_sets='KEGG_2021_Human',
    organism='human',
    outdir=None,
    no_plot=True
)

# Display top KEGG pathways for X-chromosome genes
print("\nKEGG Enrichment Results for X-chromosome Genes (Top 10):")
if x_kegg_enrichr_results.results.empty:
    print("No significant KEGG pathways found for the provided X-chromosome genes.")
else:
    display(x_kegg_enrichr_results.results.head(10))

KEGG Enrichment Results for X-chromosome Genes (Top 10):

,Gene_set,Term,Overlap,P-value,Adjusted P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes
0,KEGG_2021_Human,RNA degradation,1/79,0.023470,0.058091,0,0,51.066667,191.603929,PABPC5
1,KEGG_2021_Human,mRNA surveillance pathway,1/98,0.029046,0.058091,0,0,41.024742,145.181983,PABPC5
2,KEGG_2021_Human,RNA transport,1/186,0.054525,0.072700,0,0,21.415135,62.298669,PABPC5
3,KEGG_2021_Human,Neuroactive ligand-receptor interaction,1/341,0.098049,0.098049,0,0,11.561176,26.848409,P2RY10

The other X-linked genes (CHIC1, ZNF711, MOSPD1, PAGE5) did not appear in these top enriched pathways, suggesting they might be involved in different biological processes not covered or significantly enriched in the KEGG database for this gene set, or that their roles are less dominant in these particular pathways given the small gene list.

Kegg Analysis

In [112]:
import pandas as pd
import mygene
import gseapy

# 1. Define the gene list from the user's prompt
gene_list = [
    'CHIC1', 'P2RY10', 'PABPC5', 'ZNF711', 'PAGE5', 'MOSPD1', 'GAGE12B',
    'SH2D1A', 'IL2RG', 'TCF24', 'DCAF6', 'NLRP7', 'PEG3', 'KLK4', 'FGF2'

]

# Initialize mygene
mg = mygene.MyGeneInfo()

# Query mygene for chromosomal position and summary/name
# Using 'genomic_pos.chr' to get chromosome, 'summary' for main function
mygene_results = mg.querymany(
    gene_list,
    scopes='symbol',
    fields='genomic_pos.chr,summary',
    species='human',
    returnall=True,
    as_dataframe=True
)

gene_info_df_raw = mygene_results['out']

# Prepare a list to store data for the final table
table_data = []

# Process each gene for chromosomal info and main function
for gene_symbol in gene_list:
    chr_info = 'N/A'
    is_x_linked = 'No'
    main_function = 'Information not available.'

    if gene_symbol in gene_info_df_raw.index:
        gene_entry = gene_info_df_raw.loc[gene_symbol]

        # Handle multiple results for a gene, take the first one for simplicity
        if isinstance(gene_entry, pd.DataFrame):
            gene_entry = gene_entry.iloc[0]

        # Chromosome information
        chr_data = gene_entry.get('genomic_pos.chr')
        chromosomes = []
        if pd.notna(chr_data):
            if isinstance(chr_data, list):
                chromosomes = [str(c) for c in chr_data if pd.notna(c)]
            elif isinstance(chr_data, str):
                chromosomes = [chr_data]

            # Remove duplicates and sort for consistency
            chromosomes = sorted(list(set(chromosomes)))

            if len(chromosomes) > 0:
                chr_info = ', '.join(chromosomes)
                if 'X' in chromosomes:
                    is_x_linked = 'Yes'

        # Main function (summary)
        summary = gene_entry.get('summary')
        if pd.notna(summary):
            # Take the first sentence of the summary
            main_function = summary.split('.')[0] + '.' if '.' in summary else summary

    table_data.append({
        'Gene': gene_symbol,
        'Chromosome': chr_info,
        'Is X-linked': is_x_linked,
        'Main Function/Description': main_function,
        'Implantation Related Pathway': 'Not identified' # Placeholder, will update after KEGG
    })

gene_details_df = pd.DataFrame(table_data)


# 2. Perform KEGG enrichment analysis
enrichr_results = gseapy.enrichr(
    gene_list=gene_list,
    gene_sets='KEGG_2021_Human',
    organism='human',
    outdir=None,
    no_plot=True
)

# 3. Process KEGG results for implantation-related pathways
implantation_pathways = []
if not enrichr_results.results.empty:
    kegg_df = enrichr_results.results

    # Define keywords for implantation-related pathways
    keywords = ['implantation', 'reproduction', 'fertility', 'estrogen', 'progesterone', 'decidua', 'pregnancy', 'endocrine', 'uterus', 'trophoblast']

    # Filter pathways that contain any of the keywords
    for idx, row in kegg_df.iterrows():
        pathway_name = row['Term'].lower()
        if any(keyword in pathway_name for keyword in keywords):
            implantation_pathways.append({
                'Pathway': row['Term'],
                'Genes': row['Genes'] # Genes associated with this pathway
            })

# Update the gene_details_df with implantation-related pathway information
for i, row in gene_details_df.iterrows():
    gene_symbol = row['Gene']
    associated_pathways = []
    for pathway_info in implantation_pathways:
        # Split the 'Genes' string into a list and check if the gene_symbol is present
        pathway_genes = [g.strip() for g in pathway_info['Genes'].split(';')]
        if gene_symbol in pathway_genes:
            associated_pathways.append(pathway_info['Pathway'])

    if len(associated_pathways) > 0:
        gene_details_df.loc[i, 'Implantation Related Pathway'] = '; '.join(associated_pathways)

# Display the final table
display(gene_details_df)

print("\n--- Full KEGG Enrichment Results (Top 10) ---")
if not enrichr_results.results.empty:
    display(enrichr_results.results.head(10))
else:
    print("No KEGG enrichment results were found for the provided genes.")

1 input query terms found dup hits:	[('GAGE12B', 2)]

,Gene,Chromosome,Is X-linked,Main Function/Description,Implantation Related Pathway
0,CHIC1,X,Yes,This gene encodes a cysteine-rich hydrophobic ...,Not identified
1,P2RY10,X,Yes,The protein encoded by this gene belongs to th...,Not identified
2,PABPC5,X,Yes,This gene encodes a protein that binds to the ...,Not identified
3,ZNF711,X,Yes,This gene encodes a zinc finger protein of unk...,Not identified
4,PAGE5,X,Yes,This gene is a member of family of proteins th...,Not identified
5,MOSPD1,X,Yes,Predicted to be involved in negative regulatio...,Not identified
6,GAGE12B,X,Yes,Information not available.,Not identified
7,SH2D1A,X,Yes,This gene encodes a protein that plays a major...,Not identified
8,IL2RG,X,Yes,The protein encoded by this gene is an importa...,Not identified
9,TCF24,8,No,Predicted to enable DNA-binding transcription ...,Not identified
10,DCAF6,1,No,The protein encoded by this gene is a ligand-d...,Not identified
11,NLRP7,N/A,No,"This gene encodes a member of the NACHT, leuci...",Not identified
12,PEG3,19,No,"In human, ZIM2 and PEG3 are treated as two dis...",Not identified
13,KLK4,19,No,Kallikreins are a subgroup of serine proteases...,Not identified
14,FGF2,4,No,The protein encoded by this gene is a member o...,Not identified

--- Full KEGG Enrichment Results (Top 10) ---

,Gene_set,Term,Overlap,P-value,Adjusted P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes
0,KEGG_2021_Human,Primary immunodeficiency,1/38,0.028134,0.191183,0,0,38.509653,137.509923,IL2RG
1,KEGG_2021_Human,PI3K-Akt signaling pathway,2/354,0.028175,0.191183,0,0,8.580857,30.627697,IL2RG;FGF2
2,KEGG_2021_Human,Inflammatory bowel disease,1/65,0.047672,0.191183,0,0,22.233259,67.664721,IL2RG
3,KEGG_2021_Human,Melanoma,1/72,0.052678,0.191183,0,0,20.034205,58.971857,FGF2
4,KEGG_2021_Human,RNA degradation,1/79,0.057659,0.191183,0,0,18.229853,52.013636,PABPC5
5,KEGG_2021_Human,Pathways in cancer,2/531,0.058807,0.191183,0,0,5.658281,16.032749,IL2RG;FGF2
6,KEGG_2021_Human,Th1 and Th2 cell differentiation,1/92,0.066844,0.191183,0,0,15.615385,42.245702,IL2RG
7,KEGG_2021_Human,mRNA surveillance pathway,1/98,0.071055,0.191183,0,0,14.645066,38.725871,PABPC5
8,KEGG_2021_Human,Viral protein interaction with cytokine and cy...,1/100,0.072455,0.191183,0,0,14.347763,37.659814,IL2RG
9,KEGG_2021_Human,Th17 cell differentiation,1/107,0.077339,0.191183,0,0,13.395553,34.286682,IL2RG

In [113]:
gene_details_df

,Gene,Chromosome,Is X-linked,Main Function/Description,Implantation Related Pathway
0,CHIC1,X,Yes,This gene encodes a cysteine-rich hydrophobic ...,Not identified
1,P2RY10,X,Yes,The protein encoded by this gene belongs to th...,Not identified
2,PABPC5,X,Yes,This gene encodes a protein that binds to the ...,Not identified
3,ZNF711,X,Yes,This gene encodes a zinc finger protein of unk...,Not identified
4,PAGE5,X,Yes,This gene is a member of family of proteins th...,Not identified
5,MOSPD1,X,Yes,Predicted to be involved in negative regulatio...,Not identified
6,GAGE12B,X,Yes,Information not available.,Not identified
7,SH2D1A,X,Yes,This gene encodes a protein that plays a major...,Not identified
8,IL2RG,X,Yes,The protein encoded by this gene is an importa...,Not identified
9,TCF24,8,No,Predicted to enable DNA-binding transcription ...,Not identified
10,DCAF6,1,No,The protein encoded by this gene is a ligand-d...,Not identified
11,NLRP7,N/A,No,"This gene encodes a member of the NACHT, leuci...",Not identified
12,PEG3,19,No,"In human, ZIM2 and PEG3 are treated as two dis...",Not identified
13,KLK4,19,No,Kallikreins are a subgroup of serine proteases...,Not identified
14,FGF2,4,No,The protein encoded by this gene is a member o...,Not identified

In [114]:
import pandas as pd
import matplotlib.pyplot as plt

# Ensure gene_details_df is available from the previous cell's execution
# Create a copy to avoid modifying the original DataFrame if it's used elsewhere
df_to_image = gene_details_df.copy()

# Drop the 'Implantation Related Pathway' column as requested
df_to_image = df_to_image.drop(columns=['Implantation Related Pathway'])

# Prepare figure for the table
# Adjust figsize dynamically based on the number of rows and columns
rows_per_inch = 0.35 # Estimate height needed per row
cols_per_inch = 2.5 # Estimate width needed per column

fig_width = df_to_image.shape[1] * cols_per_inch # Base width on number of columns
fig_height = df_to_image.shape[0] * rows_per_inch + 1 # Base height on number of rows + padding

fig, ax = plt.subplots(figsize=(fig_width, fig_height))
ax.axis('off')

# Add a title for the table
ax.set_title('Gene Details (Excluding Implantation Pathways)', loc='center', fontsize=16, pad=10)

# Create table
table = ax.table(
    cellText=df_to_image.values,
    colLabels=df_to_image.columns,
    loc='center',
    cellLoc='left' # Align cell text to the left
)

table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1, 1.5) # Adjust scale for better readability, especially row height

# Auto-adjust column widths for better presentation
table.auto_set_column_width(col=list(range(len(df_to_image.columns))))

plt.tight_layout()

# Save as PNG
output_filename = "gene_details_table.png"
plt.savefig(
    output_filename,
    bbox_inches='tight',
    dpi=300
)

plt.close()

print(f"Table saved as {output_filename}")

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13608\4204868326.py:40: UserWarning: Tight layout not applied. The left and right margins cannot be made large enough to accommodate all Axes decorations.
  plt.tight_layout()

Table saved as gene_details_table.png