# Download the files

In [1]:
import pandas as  pd
esp_counts = pd.read_csv(r"F:\biotecnika\data stored\originalGSE108966\Original_GSE108966_ESPcounts.csv")
display(esp_counts.head(5))
display(esp_counts.shape)
print("df info:")
esp_counts.info()

,Unnamed: 0,13586,13590,13606,13610,13879,13880,13881,13882,13885,...,141261,141262,141263,141264,141266,141270,141271,141272,141273,141299
0,hsa-let-7a-3p_MIMAT0004481,289,525,47,40,314,431,285,196,379,...,757,214,452,944,576,95,112,151,165,592
1,hsa-let-7a-5p_MIMAT0000062,775079,182340,20735,17309,168588,294670,134715,434052,351995,...,189992,99116,171763,223033,220784,80169,60976,157055,98825,192867
2,hsa-let-7a-2-3p_MIMAT0010195,2,2,0,0,4,0,4,0,6,...,4,1,0,0,4,0,0,0,0,1
3,hsa-let-7b-5p_MIMAT0000063,89304,31151,1003,1387,24902,31986,18181,55036,52102,...,16808,12060,15282,23532,33422,6918,4908,10242,6323,22962
4,hsa-let-7b-3p_MIMAT0004482,109,106,24,18,191,304,195,127,239,...,346,64,220,391,557,17,36,51,61,238

(2588, 92)

df info:
<class 'pandas.DataFrame'>
RangeIndex: 2588 entries, 0 to 2587
Data columns (total 92 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2588 non-null   str
 1   13586       2588 non-null   int64
 2   13590       2588 non-null   int64
 3   13606       2588 non-null   int64
 4   13610       2588 non-null   int64
 5   13879       2588 non-null   int64
 6   13880       2588 non-null   int64
 7   13881       2588 non-null   int64
 8   13882       2588 non-null   int64
 9   13885       2588 non-null   int64
 10  13886       2588 non-null   int64
 11  13887       2588 non-null   int64
 12  13888       2588 non-null   int64
 13  13889       2588 non-null   int64
 14  13890       2588 non-null   int64
 15  13893       2588 non-null   int64
 16  13894       2588 non-null   int64
 17  13899       2588 non-null   int64
 18  13900       2588 non-null   int64
 19  13901       2588 non-null   int64
 20  13902       2588 non-null   int64
 21  13905       2588 non-null   int64
 22  13906       2588 non-null   int64
 23  13907       2588 non-null   int64
 24  13908       2588 non-null   int64
 25  13909       2588 non-null   int64
 26  13910       2588 non-null   int64
 27  13942       2588 non-null   int64
 28  13943       2588 non-null   int64
 29  13950       2588 non-null   int64
 30  13951       2588 non-null   int64
 31  131041      2588 non-null   int64
 32  131042      2588 non-null   int64
 33  131043      2588 non-null   int64
 34  131044      2588 non-null   int64
 35  131045      2588 non-null   int64
 36  131046      2588 non-null   int64
 37  131047      2588 non-null   int64
 38  131048      2588 non-null   int64
 39  131051      2588 non-null   int64
 40  131052      2588 non-null   int64
 41  131055      2588 non-null   int64
 42  131056      2588 non-null   int64
 43  131057      2588 non-null   int64
 44  131058      2588 non-null   int64
 45  131059      2588 non-null   int64
 46  131060      2588 non-null   int64
 47  131061      2588 non-null   int64
 48  131062      2588 non-null   int64
 49  131063      2588 non-null   int64
 50  131064      2588 non-null   int64
 51  131065      2588 non-null   int64
 52  131066      2588 non-null   int64
 53  131067      2588 non-null   int64
 54  131068      2588 non-null   int64
 55  131204      2588 non-null   int64
 56  131205      2588 non-null   int64
 57  131206      2588 non-null   int64
 58  131207      2588 non-null   int64
 59  131208      2588 non-null   int64
 60  131209      2588 non-null   int64
 61  131210      2588 non-null   int64
 62  131211      2588 non-null   int64
 63  131212      2588 non-null   int64
 64  131213      2588 non-null   int64
 65  131214      2588 non-null   int64
 66  131215      2588 non-null   int64
 67  140417      2588 non-null   int64
 68  140418      2588 non-null   int64
 69  140419      2588 non-null   int64
 70  140420      2588 non-null   int64
 71  140421      2588 non-null   int64
 72  140422      2588 non-null   int64
 73  140424      2588 non-null   int64
 74  140431      2588 non-null   int64
 75  140432      2588 non-null   int64
 76  140433      2588 non-null   int64
 77  140434      2588 non-null   int64
 78  140435      2588 non-null   int64
 79  140436      2588 non-null   int64
 80  140438      2588 non-null   int64
 81  141259      2588 non-null   int64
 82  141261      2588 non-null   int64
 83  141262      2588 non-null   int64
 84  141263      2588 non-null   int64
 85  141264      2588 non-null   int64
 86  141266      2588 non-null   int64
 87  141270      2588 non-null   int64
 88  141271      2588 non-null   int64
 89  141272      2588 non-null   int64
 90  141273      2588 non-null   int64
 91  141299      2588 non-null   int64
dtypes: int64(91), str(1)
memory usage: 1.8 MB

In [2]:
import pandas as  pd
est_counts = pd.read_csv(r"F:\biotecnika\data stored\originalGSE108966\Original_GSE108966_ESTcounts.csv")
display(est_counts.head(5))
display(est_counts.shape)
print("df info:")
est_counts.info()

,Unnamed: 0,ERTK11LH2E,ERTK11LH8E,NOT1209LH2B,NOT1209LH2E,NOT1209LH8B,NOT1209LH8E,NOT1210LH2B,NOT1210LH2E,NOT1210LH8B,...,NOTNV48LH8E,NOTNV52LH8E,NOTNV58LH8E,NOTNV59LH8E,NOTNV62LH8E,NOTNV71LH8E,NOTNV73LH8E,NOTNV75LH2E,NOTNV75LH8E,NOTNV78LH8E
0,hsa-let-7a-3p_MIMAT0004481,375,1091,2,319,2,1034,1,583,0,...,338,118,976,150,117,581,1124,97,46,250
1,hsa-let-7a-5p_MIMAT0000062,210095,279622,12090,174320,15234,232909,13495,204129,3642,...,122341,164427,297708,155401,156879,517926,605584,147492,143717,118022
2,hsa-let-7a-2-3p_MIMAT0010195,0,2,0,1,0,1,0,0,0,...,0,0,0,2,0,2,2,0,0,0
3,hsa-let-7b-5p_MIMAT0000063,10134,25660,1899,13416,1762,21021,887,12338,286,...,8588,9281,24282,13143,11056,30509,48452,9891,10357,6021
4,hsa-let-7b-3p_MIMAT0004482,110,283,24,128,26,236,36,120,51,...,130,22,443,73,45,301,438,27,24,50

(2588, 112)

df info:
<class 'pandas.DataFrame'>
RangeIndex: 2588 entries, 0 to 2587
Columns: 112 entries, Unnamed: 0 to NOTNV78LH8E
dtypes: int64(111), str(1)
memory usage: 2.2 MB

In [3]:
from pathlib import Path

soft_path = Path(
    r"F:\biotecnika\data stored\originalGSE108966\Original_GSE108966_family.soft"
)

records = []

for line in soft_path.read_text(encoding="utf-8", errors="replace").splitlines():
    if line.startswith("^") or line.startswith("!"):
        if "=" in line:
            key, value = line.split("=", 1)
            records.append({
                "key": key.strip(),
                "value": value.strip()
            })

family_gse = pd.DataFrame(records)

# GSE series details
gse_details = family_gse.iloc[:29].reset_index(drop=True)
display(gse_details)

# Series sample IDs
sample_ids = family_gse[
    family_gse["key"].eq("!Series_sample_id")
].reset_index(drop=True)

display(sample_ids)

,key,value
0,^DATABASE,GeoMiame
1,!Database_name,Gene Expression Omnibus (GEO)
2,!Database_institute,NCBI NLM NIH
3,!Database_web_link,http://www.ncbi.nlm.nih.gov/geo
4,!Database_email,geo@ncbi.nlm.nih.gov
5,^SERIES,GSE108966
6,!Series_title,A comprehensive two-centre RNA-seq study revea...
7,!Series_geo_accession,GSE108966
8,!Series_status,Public on Jul 18 2019
9,!Series_submission_date,Jan 09 2018
10,!Series_last_update_date,Jul 18 2019
11,!Series_pubmed_id,30477193
12,!Series_summary,Study question: Does a comprehensive study inv...
13,!Series_summary,"Summary answer: Several annotated miRNAs, not ..."
14,!Series_summary,What is known already: The involvement of miRN...
15,!Series_summary,"Participants/materials, setting, methods: A to..."
16,!Series_summary,Main results and the role of chance: Among fer...
17,!Series_overall_design,Our current study recruited 39 fertile women a...
18,!Series_type,Non-coding RNA profiling by high throughput se...
19,!Series_contributor,"Kadri,,Rekker"
20,!Series_contributor,"Signe,,Altmäe"
21,!Series_contributor,"Marina,,Suhorutshenko"
22,!Series_contributor,"Maire,,Peters"
23,!Series_contributor,"Juan,F,Martinez-Blanch"
24,!Series_contributor,"Francisco,M,Codoñer"
25,!Series_contributor,"Felipe,,Vilella"
26,!Series_contributor,"Carlos,,Simón"
27,!Series_contributor,"Andres,,Salumets"
28,!Series_contributor,"Agne,,Velthut-Meikas"

                   key       value
0    !Series_sample_id  GSM2916612
1    !Series_sample_id  GSM2916613
2    !Series_sample_id  GSM2916614
3    !Series_sample_id  GSM2916615
4    !Series_sample_id  GSM2916616
..                 ...         ...
197  !Series_sample_id  GSM2916809
198  !Series_sample_id  GSM2916810
199  !Series_sample_id  GSM2916811
200  !Series_sample_id  GSM2916812
201  !Series_sample_id  GSM2916813

[202 rows x 2 columns]

In [4]:
import pandas as pd

file_path = r"F:\biotecnika\data stored\originalGSE108966\Original_GSE108966_series_matrix (1).txt"


with open(file_path, "r", encoding="utf-8") as f:
    for i in range(60):
        print(f.readline().rstrip())

!Series_title	"A comprehensive two-centre RNA-seq study reveals changes in endometrial and blood miRNome at mid-secretory phase in fertile women and in patients with recurrent implantation failure"
!Series_geo_accession	"GSE108966"
!Series_status	"Public on Jul 18 2019"
!Series_submission_date	"Jan 09 2018"
!Series_last_update_date	"Jul 18 2019"
!Series_pubmed_id	"30477193"
!Series_summary	"Study question: Does a comprehensive study involving two different population cohorts and small RNA sequencing from endometrium and blood reveal new endometrial receptivity-related microRNAs (miRNAs) in healthy conditions and in women with recurrent implantation failure (RIF)?"
!Series_summary	"Summary answer: Several annotated miRNAs, not previously associated with endometrial receptivity, as well as one novel miRNA were found as differentially expressed between early secretory vs. mid-secretory phase samples in addition to miRNAs dysregulated in RIF patients."
!Series_summary	"What is known already: The involvement of miRNAs in mid-secretory endometrial functions has been shown and aberrant expression of miRNAs in RIF has been identified in a few previous studies, but not from whole blood samples. However, as the analysis settings and platforms have been different and a small number of samples has been analysed, there is no consensus about the miRNAs involved in endometrial receptivity and dysfunction."
!Series_summary	"Participants/materials, setting, methods: A total of 116 endometrial and 114 blood samples were subjected to Illumina small RNA sequencing. Identification of annotated and novel miRNAs from sequencing reads was performed by miRDeep2 algorithm. miRNAs that had significantly altered levels between the study groups in both EST and ESP datasets were considered as differentially expressed. Ingenuity Pathway Analysis was applied for identifying miRNA target genes and respective canonical pathways from the matched mRNA analysis from the same samples. Custom TaqMan Small RNA assay was used for the validation of novel miRNA (chr2_4401) levels from paired early secretory and mid-secretory endometrial samples."
!Series_summary	"Main results and the role of chance: Among fertile women, 91 differentially expressed miRNAs were identified in mid-secretory vs. early secretory endometrium, while no differentially expressed miRNAs were found in the corresponding blood samples. The comparison of mid-secretory phase samples between fertile women and RIF patients revealed 21 differentially expressed miRNAs from endometrium and one from blood samples. miRNA target gene prediction analysis using our mRNA sequencing data from the matched samples detected several canonical pathways to be involved in mid-secretory endometrial functions, including JAK/STAT signalling, leptin signalling and growth hormone signalling. Moreover, JAK/STAT signalling pathway was also revealed in miRNA target analysis of mid-secretory endometrium from RIF patients when compared to fertile women. Further, our study results highlight the involvement of miR-30 and miR-200 families in endometrial receptivity, and miR-424-5p in the development of endometrial dysfunction. We identified several novel miRNAs, of which miRNA chr2_4401, being 37-fold up-regulated in mid-secretory phase, has a potential role in the mid-secretory endometrial functions. From blood samples we identified miR-30a-5p as a possible marker of infertility related to RIF."
!Series_overall_design	"Our current study recruited 39 fertile women and 38 infertile RIF patients from Estonia (EST) and Spain (ESP). Paired endometrial and blood samples were collected at early secretory and mid-secretory phases from fertile women and at mid-secretory phase from infertile RIF patients. This is the largest miRNA endometrial receptivity study to date with novel aspects of combining matched samples of endometrium and blood from two different population cohorts."
!Series_type	"Non-coding RNA profiling by high throughput sequencing"
!Series_contributor	"Kadri,,Rekker"
!Series_contributor	"Signe,,Altmäe"
!Series_contributor	"Marina,,Suhorutshenko"
!Series_contributor	"Maire,,Peters"
!Series_contributor	"Juan,F,Martinez-Blanch"
!Series_contributor	"Francisco,M,Codoñer"
!Series_contributor	"Felipe,,Vilella"
!Series_contributor	"Carlos,,Simón"
!Series_contributor	"Andres,,Salumets"
!Series_contributor	"Agne,,Velthut-Meikas"
!Series_sample_id	"GSM2916612 GSM2916613 GSM2916614 GSM2916615 GSM2916616 GSM2916617 GSM2916618 GSM2916619 GSM2916620 GSM2916621 GSM2916622 GSM2916623 GSM2916624 GSM2916625 GSM2916626 GSM2916627 GSM2916628 GSM2916629 GSM2916630 GSM2916631 GSM2916632 GSM2916633 GSM2916634 GSM2916635 GSM2916636 GSM2916637 GSM2916638 GSM2916639 GSM2916640 GSM2916641 GSM2916642 GSM2916643 GSM2916644 GSM2916645 GSM2916646 GSM2916647 GSM2916648 GSM2916649 GSM2916650 GSM2916651 GSM2916652 GSM2916653 GSM2916654 GSM2916655 GSM2916656 GSM2916657 GSM2916658 GSM2916659 GSM2916660 GSM2916661 GSM2916662 GSM2916663 GSM2916664 GSM2916665 GSM2916666 GSM2916667 GSM2916668 GSM2916669 GSM2916670 GSM2916671 GSM2916672 GSM2916673 GSM2916674 GSM2916675 GSM2916676 GSM2916677 GSM2916678 GSM2916679 GSM2916680 GSM2916681 GSM2916682 GSM2916683 GSM2916684 GSM2916685 GSM2916686 GSM2916687 GSM2916688 GSM2916689 GSM2916690 GSM2916691 GSM2916692 GSM2916693 GSM2916694 GSM2916695 GSM2916696 GSM2916697 GSM2916698 GSM2916699 GSM2916700 GSM2916701 GSM2916702 GSM2916703 GSM2916704 GSM2916705 GSM2916706 GSM2916707 GSM2916708 GSM2916709 GSM2916710 GSM2916711 GSM2916712 GSM2916713 GSM2916714 GSM2916715 GSM2916716 GSM2916717 GSM2916718 GSM2916719 GSM2916720 GSM2916721 GSM2916722 GSM2916723 GSM2916724 GSM2916725 GSM2916726 GSM2916727 GSM2916728 GSM2916729 GSM2916730 GSM2916731 GSM2916732 GSM2916733 GSM2916734 GSM2916735 GSM2916736 GSM2916737 GSM2916738 GSM2916739 GSM2916740 GSM2916741 GSM2916742 GSM2916743 GSM2916744 GSM2916745 GSM2916746 GSM2916747 GSM2916748 GSM2916749 GSM2916750 GSM2916751 GSM2916752 GSM2916753 GSM2916754 GSM2916755 GSM2916756 GSM2916757 GSM2916758 GSM2916759 GSM2916760 GSM2916761 GSM2916762 GSM2916763 GSM2916764 GSM2916765 GSM2916766 GSM2916767 GSM2916768 GSM2916769 GSM2916770 GSM2916771 GSM2916772 GSM2916773 GSM2916774 GSM2916775 GSM2916776 GSM2916777 GSM2916778 GSM2916779 GSM2916780 GSM2916781 GSM2916782 GSM2916783 GSM2916784 GSM2916785 GSM2916786 GSM2916787 GSM2916788 GSM2916789 GSM2916790 GSM2916791 GSM2916792 GSM2916793 GSM2916794 GSM2916795 GSM2916796 GSM2916797 GSM2916798 GSM2916799 GSM2916800 GSM2916801 GSM2916802 GSM2916803 GSM2916804 GSM2916805 GSM2916806 GSM2916807 GSM2916808 GSM2916809 GSM2916810 GSM2916811 GSM2916812 GSM2916813 "
!Series_contact_name	"Agne,,Velthut-Meikas"
!Series_contact_department	"Department of Chemistry and Biotechnology"
!Series_contact_institute	"Tallinn University of Technology"
!Series_contact_address	"Akadeemia tee 15"
!Series_contact_city	"Tallinn"
!Series_contact_zip/postal_code	"12618"
!Series_contact_country	"Estonia"
!Series_supplementary_file	"ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE108nnn/GSE108966/suppl/GSE108966_ESPcounts.csv.gz"
!Series_supplementary_file	"ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE108nnn/GSE108966/suppl/GSE108966_ESTcounts.csv.gz"
!Series_platform_id	"GPL16791"
!Series_platform_taxid	"9606"
!Series_sample_taxid	"9606"
!Series_relation	"BioProject: https://www.ncbi.nlm.nih.gov/bioproject/PRJNA429257"
!Series_relation	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRP128555"

!Sample_title	"ERTK11LH2E"	"ERTK11LH8E"	"NOT1209LH2B"	"NOT1209LH2E"	"NOT1209LH8B"	"NOT1209LH8E"	"NOT1210LH2B"	"NOT1210LH2E"	"NOT1210LH8B"	"NOT1210LH8E"	"NOT1213LH2B"	"NOT1213LH2E"	"NOT1213LH8B"	"NOT1213LH8E"	"NOT1325LH8B"	"NOT1325LH8E"	"NOTNV01LH2B"	"NOTNV01LH2E"	"NOTNV01LH8B"	"NOTNV01LH8E"	"NOTNV02LH2B"	"NOTNV02LH2E"	"NOTNV02LH8B"	"NOTNV02LH8E"	"NOTNV03LH2B"	"NOTNV03LH2E"	"NOTNV03LH8B"	"NOTNV03LH8E"	"NOTNV04LH2B"	"NOTNV04LH2E"	"NOTNV04LH8B"	"NOTNV04LH8E"	"NOTNV06LH2B"	"NOTNV06LH2E"	"NOTNV06LH8B"	"NOTNV06LH8E"	"NOTNV09LH2B"	"NOTNV09LH2E"	"NOTNV09LH8B"	"NOTNV09LH8E"	"NOTNV11LH2B"	"NOTNV11LH2E"	"NOTNV11LH8B"	"NOTNV11LH8E"	"NOTNV12LH2B"	"NOTNV12LH2E"	"NOTNV12LH8B"	"NOTNV12LH8E"	"NOTNV13LH2B"	"NOTNV13LH2E"	"NOTNV13LH8B"	"NOTNV13LH8E"	"NOTNV15LH2B"	"NOTNV15LH2E"	"NOTNV15LH8B"	"NOTNV15LH8E"	"NOTNV16LH2B"	"NOTNV16LH2E"	"NOTNV16LH8B"	"NOTNV16LH8E"	"NOTNV18LH2B"	"NOTNV18LH2E"	"NOTNV18LH8B"	"NOTNV18LH8E"	"NOTNV24LH2B"	"NOTNV24LH2E"	"NOTNV24LH8B"	"NOTNV24LH8E"	"NOTNV25LH2B"	"NOTNV25LH2E"	"NOTNV25LH8B"	"NOTNV25LH8E"	"NOTNV27LH8B"	"NOTNV27LH8E"	"NOTNV29LH8E"	"NOTNV30LH8B"	"NOTNV30LH8E"	"NOTNV32LH8B"	"NOTNV32LH8E"	"NOTNV33LH8B"	"NOTNV33LH8E"	"NOTNV35LH8B"	"NOTNV35LH8E"	"NOTNV36LH8B"	"NOTNV36LH8E"	"NOTNV38LH8B"	"NOTNV38LH8E"	"NOTNV39LH8E"	"NOTNV40LH2B"	"NOTNV40LH2E"	"NOTNV40LH8B"	"NOTNV40LH8E"	"NOTNV41LH8B"	"NOTNV41LH8E"	"NOTNV43LH8B"	"NOTNV43LH8E"	"NOTNV44LH8B"	"NOTNV44LH8E"	"NOTNV47LH2E"	"NOTNV47LH8E"	"NOTNV48LH2E"	"NOTNV48LH8E"	"NOTNV52LH8E"	"NOTNV58LH8E"	"NOTNV59LH8E"	"NOTNV62LH8E"	"NOTNV71LH8E"	"NOTNV73LH8E"	"NOTNV75LH2E"	"NOTNV75LH8E"	"NOTNV78LH8E"	"13586"	"13590"	"13606"	"13610"	"13879"	"13880"	"13881"	"13882"	"13885"	"13886"	"13887"	"13888"	"13889"	"13890"	"13893"	"13894"	"13899"	"13900"	"13901"	"13902"	"13905"	"13906"	"13907"	"13908"	"13909"	"13910"	"13942"	"13943"	"13950"	"13951"	"131041"	"131042"	"131043"	"131044"	"131045"	"131046"	"131047"	"131048"	"131051"	"131052"	"131055"	"131056"	"131057"	"131058"	"131059"	"131060"	"131061"	"131062"	"131063"	"131064"	"131065"	"131066"	"131067"	"131068"	"131204"	"131205"	"131206"	"131207"	"131208"	"131209"	"131210"	"131211"	"131212"	"131213"	"131214"	"131215"	"140417"	"140418"	"140419"	"140420"	"140421"	"140422"	"140424"	"140431"	"140432"	"140433"	"140434"	"140435"	"140436"	"140438"	"141259"	"141261"	"141262"	"141263"	"141264"	"141266"	"141270"	"141271"	"141272"	"141273"	"141299"
!Sample_geo_accession	"GSM2916612"	"GSM2916613"	"GSM2916614"	"GSM2916615"	"GSM2916616"	"GSM2916617"	"GSM2916618"	"GSM2916619"	"GSM2916620"	"GSM2916621"	"GSM2916622"	"GSM2916623"	"GSM2916624"	"GSM2916625"	"GSM2916626"	"GSM2916627"	"GSM2916628"	"GSM2916629"	"GSM2916630"	"GSM2916631"	"GSM2916632"	"GSM2916633"	"GSM2916634"	"GSM2916635"	"GSM2916636"	"GSM2916637"	"GSM2916638"	"GSM2916639"	"GSM2916640"	"GSM2916641"	"GSM2916642"	"GSM2916643"	"GSM2916644"	"GSM2916645"	"GSM2916646"	"GSM2916647"	"GSM2916648"	"GSM2916649"	"GSM2916650"	"GSM2916651"	"GSM2916652"	"GSM2916653"	"GSM2916654"	"GSM2916655"	"GSM2916656"	"GSM2916657"	"GSM2916658"	"GSM2916659"	"GSM2916660"	"GSM2916661"	"GSM2916662"	"GSM2916663"	"GSM2916664"	"GSM2916665"	"GSM2916666"	"GSM2916667"	"GSM2916668"	"GSM2916669"	"GSM2916670"	"GSM2916671"	"GSM2916672"	"GSM2916673"	"GSM2916674"	"GSM2916675"	"GSM2916676"	"GSM2916677"	"GSM2916678"	"GSM2916679"	"GSM2916680"	"GSM2916681"	"GSM2916682"	"GSM2916683"	"GSM2916684"	"GSM2916685"	"GSM2916686"	"GSM2916687"	"GSM2916688"	"GSM2916689"	"GSM2916690"	"GSM2916691"	"GSM2916692"	"GSM2916693"	"GSM2916694"	"GSM2916695"	"GSM2916696"	"GSM2916697"	"GSM2916698"	"GSM2916699"	"GSM2916700"	"GSM2916701"	"GSM2916702"	"GSM2916703"	"GSM2916704"	"GSM2916705"	"GSM2916706"	"GSM2916707"	"GSM2916708"	"GSM2916709"	"GSM2916710"	"GSM2916711"	"GSM2916712"	"GSM2916713"	"GSM2916714"	"GSM2916715"	"GSM2916716"	"GSM2916717"	"GSM2916718"	"GSM2916719"	"GSM2916720"	"GSM2916721"	"GSM2916722"	"GSM2916723"	"GSM2916724"	"GSM2916725"	"GSM2916726"	"GSM2916727"	"GSM2916728"	"GSM2916729"	"GSM2916730"	"GSM2916731"	"GSM2916732"	"GSM2916733"	"GSM2916734"	"GSM2916735"	"GSM2916736"	"GSM2916737"	"GSM2916738"	"GSM2916739"	"GSM2916740"	"GSM2916741"	"GSM2916742"	"GSM2916743"	"GSM2916744"	"GSM2916745"	"GSM2916746"	"GSM2916747"	"GSM2916748"	"GSM2916749"	"GSM2916750"	"GSM2916751"	"GSM2916752"	"GSM2916753"	"GSM2916754"	"GSM2916755"	"GSM2916756"	"GSM2916757"	"GSM2916758"	"GSM2916759"	"GSM2916760"	"GSM2916761"	"GSM2916762"	"GSM2916763"	"GSM2916764"	"GSM2916765"	"GSM2916766"	"GSM2916767"	"GSM2916768"	"GSM2916769"	"GSM2916770"	"GSM2916771"	"GSM2916772"	"GSM2916773"	"GSM2916774"	"GSM2916775"	"GSM2916776"	"GSM2916777"	"GSM2916778"	"GSM2916779"	"GSM2916780"	"GSM2916781"	"GSM2916782"	"GSM2916783"	"GSM2916784"	"GSM2916785"	"GSM2916786"	"GSM2916787"	"GSM2916788"	"GSM2916789"	"GSM2916790"	"GSM2916791"	"GSM2916792"	"GSM2916793"	"GSM2916794"	"GSM2916795"	"GSM2916796"	"GSM2916797"	"GSM2916798"	"GSM2916799"	"GSM2916800"	"GSM2916801"	"GSM2916802"	"GSM2916803"	"GSM2916804"	"GSM2916805"	"GSM2916806"	"GSM2916807"	"GSM2916808"	"GSM2916809"	"GSM2916810"	"GSM2916811"	"GSM2916812"	"GSM2916813"
!Sample_status	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"	"Public on Jul 18 2019"

In [5]:
with open(file_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

start = next(i for i, line in enumerate(lines)
             if "!series_matrix_table_begin" in line)

print("Table starts at line:", start)

for line in lines[start:start+5]:
    print(repr(line))

Table starts at line: 78
'!series_matrix_table_begin\n'
'"ID_REF"\t"GSM2916612"\t"GSM2916613"\t"GSM2916614"\t"GSM2916615"\t"GSM2916616"\t"GSM2916617"\t"GSM2916618"\t"GSM2916619"\t"GSM2916620"\t"GSM2916621"\t"GSM2916622"\t"GSM2916623"\t"GSM2916624"\t"GSM2916625"\t"GSM2916626"\t"GSM2916627"\t"GSM2916628"\t"GSM2916629"\t"GSM2916630"\t"GSM2916631"\t"GSM2916632"\t"GSM2916633"\t"GSM2916634"\t"GSM2916635"\t"GSM2916636"\t"GSM2916637"\t"GSM2916638"\t"GSM2916639"\t"GSM2916640"\t"GSM2916641"\t"GSM2916642"\t"GSM2916643"\t"GSM2916644"\t"GSM2916645"\t"GSM2916646"\t"GSM2916647"\t"GSM2916648"\t"GSM2916649"\t"GSM2916650"\t"GSM2916651"\t"GSM2916652"\t"GSM2916653"\t"GSM2916654"\t"GSM2916655"\t"GSM2916656"\t"GSM2916657"\t"GSM2916658"\t"GSM2916659"\t"GSM2916660"\t"GSM2916661"\t"GSM2916662"\t"GSM2916663"\t"GSM2916664"\t"GSM2916665"\t"GSM2916666"\t"GSM2916667"\t"GSM2916668"\t"GSM2916669"\t"GSM2916670"\t"GSM2916671"\t"GSM2916672"\t"GSM2916673"\t"GSM2916674"\t"GSM2916675"\t"GSM2916676"\t"GSM2916677"\t"GSM2916678"\t"GSM2916679"\t"GSM2916680"\t"GSM2916681"\t"GSM2916682"\t"GSM2916683"\t"GSM2916684"\t"GSM2916685"\t"GSM2916686"\t"GSM2916687"\t"GSM2916688"\t"GSM2916689"\t"GSM2916690"\t"GSM2916691"\t"GSM2916692"\t"GSM2916693"\t"GSM2916694"\t"GSM2916695"\t"GSM2916696"\t"GSM2916697"\t"GSM2916698"\t"GSM2916699"\t"GSM2916700"\t"GSM2916701"\t"GSM2916702"\t"GSM2916703"\t"GSM2916704"\t"GSM2916705"\t"GSM2916706"\t"GSM2916707"\t"GSM2916708"\t"GSM2916709"\t"GSM2916710"\t"GSM2916711"\t"GSM2916712"\t"GSM2916713"\t"GSM2916714"\t"GSM2916715"\t"GSM2916716"\t"GSM2916717"\t"GSM2916718"\t"GSM2916719"\t"GSM2916720"\t"GSM2916721"\t"GSM2916722"\t"GSM2916723"\t"GSM2916724"\t"GSM2916725"\t"GSM2916726"\t"GSM2916727"\t"GSM2916728"\t"GSM2916729"\t"GSM2916730"\t"GSM2916731"\t"GSM2916732"\t"GSM2916733"\t"GSM2916734"\t"GSM2916735"\t"GSM2916736"\t"GSM2916737"\t"GSM2916738"\t"GSM2916739"\t"GSM2916740"\t"GSM2916741"\t"GSM2916742"\t"GSM2916743"\t"GSM2916744"\t"GSM2916745"\t"GSM2916746"\t"GSM2916747"\t"GSM2916748"\t"GSM2916749"\t"GSM2916750"\t"GSM2916751"\t"GSM2916752"\t"GSM2916753"\t"GSM2916754"\t"GSM2916755"\t"GSM2916756"\t"GSM2916757"\t"GSM2916758"\t"GSM2916759"\t"GSM2916760"\t"GSM2916761"\t"GSM2916762"\t"GSM2916763"\t"GSM2916764"\t"GSM2916765"\t"GSM2916766"\t"GSM2916767"\t"GSM2916768"\t"GSM2916769"\t"GSM2916770"\t"GSM2916771"\t"GSM2916772"\t"GSM2916773"\t"GSM2916774"\t"GSM2916775"\t"GSM2916776"\t"GSM2916777"\t"GSM2916778"\t"GSM2916779"\t"GSM2916780"\t"GSM2916781"\t"GSM2916782"\t"GSM2916783"\t"GSM2916784"\t"GSM2916785"\t"GSM2916786"\t"GSM2916787"\t"GSM2916788"\t"GSM2916789"\t"GSM2916790"\t"GSM2916791"\t"GSM2916792"\t"GSM2916793"\t"GSM2916794"\t"GSM2916795"\t"GSM2916796"\t"GSM2916797"\t"GSM2916798"\t"GSM2916799"\t"GSM2916800"\t"GSM2916801"\t"GSM2916802"\t"GSM2916803"\t"GSM2916804"\t"GSM2916805"\t"GSM2916806"\t"GSM2916807"\t"GSM2916808"\t"GSM2916809"\t"GSM2916810"\t"GSM2916811"\t"GSM2916812"\t"GSM2916813"\n'
'!series_matrix_table_end\n'

In [6]:
human_gr = pd.read_csv(
    r"F:\biotecnika\data stored\originalGSE108966\Original_Human.GRCh38.p13.annot.tsv",
    sep="\t",
    comment="#",
    dtype=str,
    low_memory=False
)

human_gr.head()

,GeneID,Symbol,Description,Synonyms,GeneType,EnsemblGeneID,Status,ChrAcc,ChrStart,ChrStop,Orientation,Length,GOFunctionID,GOProcessID,GOComponentID,GOFunction,GOProcess,GOComponent
0,100287102,DDX11L1,DEAD/H-box helicase 11 like 1 (pseudogene),NaN,pseudo,ENSG00000290825,active,NC_000001.11,11874,14409,positive,1652,NaN,NaN,NaN,NaN,NaN,NaN
1,653635,WASH7P,"WASP family homolog 7, pseudogene",FAM39F|WASH5P,pseudo,NaN,active,NC_000001.11,14362,29370,negative,1769,NaN,NaN,NaN,NaN,NaN,NaN
2,102466751,MIR6859-1,microRNA 6859-1,hsa-mir-6859-1,ncRNA,ENSG00000278267,active,NC_000001.11,17369,17436,negative,68,NaN,NaN,NaN,NaN,NaN,NaN
3,107985730,MIR1302-2HG,MIR1302-2 host gene,NaN,ncRNA,NaN,active,NC_000001.11,29926,31295,positive,538,NaN,NaN,NaN,NaN,NaN,NaN
4,100302278,MIR1302-2,microRNA 1302-2,MIRN1302-2|hsa-mir-1302-2,ncRNA,ENSG00000284332,active,NC_000001.11,30366,30503,positive,138,NaN,GO:0035195,NaN,NaN,miRNA-mediated gene silencing,NaN

In [7]:
# Show all column names
print(human_gr.columns.tolist())

mirnas = ["3607", "5701", "4510", "378g"]

# Search columns containing symbol, synonym, name, alias, or identifier
search_columns = [
    column for column in human_gr.columns
    if any(
        word in column.lower()
        for word in ["symbol", "synonym", "name", "alias", "id"]
    )
]

print("Columns being searched:")
print(search_columns)

if not search_columns:
    print("No relevant columns were found.")

else:
    # Match different formats:
    # miR-3607
    # miR3607
    # MIR-3607
    # hsa-miR-3607
    # hsa_miR_3607
    pattern = r"(?i)(?:hsa[-_ ]?)?mir[-_ ]?(?:3607|5701|4510)(?!\d)"

    # Search all selected columns
    matches = (
        human_gr[search_columns]
        .fillna("")
        .astype(str)
        .apply(
            lambda col: col.str.contains(
                pattern,
                regex=True,
                na=False
            )
        )
        .any(axis=1)
    )

    # Return the COMPLETE rows
    mirna_matches = human_gr.loc[matches].copy()

    print("Number of matches:", len(mirna_matches))

    display(mirna_matches)

['GeneID', 'Symbol', 'Description', 'Synonyms', 'GeneType', 'EnsemblGeneID', 'Status', 'ChrAcc', 'ChrStart', 'ChrStop', 'Orientation', 'Length', 'GOFunctionID', 'GOProcessID', 'GOComponentID', 'GOFunction', 'GOProcess', 'GOComponent']
Columns being searched:
['GeneID', 'Symbol', 'Synonyms', 'EnsemblGeneID', 'GOFunctionID', 'GOProcessID', 'GOComponentID']
Number of matches: 5

,GeneID,Symbol,Description,Synonyms,GeneType,EnsemblGeneID,Status,ChrAcc,ChrStart,ChrStop,Orientation,Length,GOFunctionID,GOProcessID,GOComponentID,GOFunction,GOProcess,GOComponent
11132,109623460,SNORD138,"small nucleolar RNA, C/D box 138",MIR3607|mir-3607,snoRNA,NaN,active,NC_000005.10,86620506,86620568,positive,63,NaN,GO:0006396,GO:0005730,NaN,RNA processing,nucleolus
27672,100847060,MIR5701-1,microRNA 5701-1,NaN,ncRNA,ENSG00000266545,active,NC_000015.10,20940252,20940333,positive,82,NaN,NaN,NaN,NaN,NaN,NaN
27683,100847005,MIR5701-2,microRNA 5701-2,NaN,ncRNA,ENSG00000277841,active,NC_000015.10,21513959,21514040,positive,82,NaN,NaN,NaN,NaN,NaN,NaN
27696,103504741,MIR5701-3,microRNA 5701-3,hsa-mir-5701-3,ncRNA,ENSG00000264902,active,NC_000015.10,21951242,21951323,positive,82,NaN,NaN,NaN,NaN,NaN,NaN
27983,100616293,MIR4510,microRNA 4510,mir-4510,ncRNA,ENSG00000265098,active,NC_000015.10,35926856,35926923,positive,68,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
gse_id = "GSE108966"
import GEOparse

gse = GEOparse.get_GEO(
    geo=gse_id,
    destdir="."
)
sample_data = []

for gsm_name, gsm in gse.gsms.items():
    data = gsm.metadata
    
    sample_data.append({
        "Accession": gsm_name,
        "Title": data.get("title", [""])[0],
        "Source name": data.get("source_name_ch1", [""])[0]
    })

metadata = pd.DataFrame(sample_data)

display(metadata)

29-Aug-2026 12:04:04 DEBUG utils - Directory . already exists. Skipping.
29-Aug-2026 12:04:04 INFO GEOparse - File already exist: using local version.
29-Aug-2026 12:04:04 INFO GEOparse - Parsing .\GSE108966_family.soft.gz:
29-Aug-2026 12:04:04 DEBUG GEOparse - DATABASE: GeoMiame
29-Aug-2026 12:04:04 DEBUG GEOparse - SERIES: GSE108966
29-Aug-2026 12:04:04 DEBUG GEOparse - PLATFORM: GPL16791
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916612
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916613
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916614
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916615
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916616
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916617
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916618
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916619
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916620
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916621
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916622
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916623
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916624
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916625
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916626
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916627
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916628
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916629
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916630
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916631
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916632
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916633
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916634
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916635
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916636
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916637
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916638
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916639
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916640
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916641
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916642
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916643
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916644
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916645
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916646
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916647
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916648
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916649
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916650
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916651
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916652
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916653
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916654
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916655
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916656
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916657
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916658
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916659
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916660
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916661
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916662
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916663
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916664
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916665
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916666
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916667
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916668
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916669
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916670
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916671
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916672
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916673
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916674
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916675
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916676
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916677
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916678
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916679
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916680
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916681
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916682
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916683
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916684
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916685
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916686
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916687
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916688
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916689
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916690
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916691
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916692
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916693
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916694
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916695
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916696
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916697
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916698
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916699
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916700
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916701
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916702
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916703
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916704
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916705
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916706
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916707
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916708
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916709
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916710
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916711
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916712
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916713
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916714
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916715
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916716
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916717
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916718
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916719
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916720
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916721
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916722
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916723
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916724
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916725
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916726
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916727
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916728
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916729
29-Aug-2026 12:04:04 DEBUG GEOparse - SAMPLE: GSM2916730
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916731
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916732
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916733
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916734
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916735
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916736
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916737
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916738
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916739
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916740
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916741
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916742
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916743
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916744
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916745
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916746
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916747
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916748
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916749
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916750
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916751
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916752
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916753
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916754
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916755
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916756
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916757
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916758
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916759
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916760
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916761
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916762
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916763
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916764
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916765
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916766
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916767
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916768
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916769
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916770
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916771
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916772
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916773
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916774
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916775
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916776
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916777
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916778
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916779
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916780
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916781
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916782
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916783
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916784
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916785
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916786
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916787
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916788
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916789
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916790
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916791
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916792
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916793
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916794
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916795
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916796
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916797
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916798
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916799
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916800
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916801
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916802
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916803
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916804
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916805
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916806
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916807
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916808
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916809
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916810
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916811
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916812
29-Aug-2026 12:04:05 DEBUG GEOparse - SAMPLE: GSM2916813

      Accession        Title  Source name
0    GSM2916612   ERTK11LH2E  endometrium
1    GSM2916613   ERTK11LH8E  endometrium
2    GSM2916614  NOT1209LH2B        blood
3    GSM2916615  NOT1209LH2E  endometrium
4    GSM2916616  NOT1209LH8B        blood
..          ...          ...          ...
197  GSM2916809       141270        blood
198  GSM2916810       141271        blood
199  GSM2916811       141272        blood
200  GSM2916812       141273        blood
201  GSM2916813       141299  endometrium

[202 rows x 3 columns]

In [9]:
# Normalize the source-name values
metadata["Source name"] = metadata["Source name"].str.strip().str.lower()

# Separate samples
endometrium_metadata = metadata[
    metadata["Source name"].eq("endometrium")
].reset_index(drop=True)

blood_metadata = metadata[
    metadata["Source name"].eq("blood")
].reset_index(drop=True)

# Display both tables
display(endometrium_metadata)
display(blood_metadata)


print("Endometrium samples:", len(endometrium_metadata))
print("Blood samples:", len(blood_metadata))

      Accession        Title  Source name
0    GSM2916612   ERTK11LH2E  endometrium
1    GSM2916613   ERTK11LH8E  endometrium
2    GSM2916615  NOT1209LH2E  endometrium
3    GSM2916617  NOT1209LH8E  endometrium
4    GSM2916619  NOT1210LH2E  endometrium
..          ...          ...          ...
105  GSM2916805       141262  endometrium
106  GSM2916806       141263  endometrium
107  GSM2916807       141264  endometrium
108  GSM2916808       141266  endometrium
109  GSM2916813       141299  endometrium

[110 rows x 3 columns]

     Accession        Title Source name
0   GSM2916614  NOT1209LH2B       blood
1   GSM2916616  NOT1209LH8B       blood
2   GSM2916618  NOT1210LH2B       blood
3   GSM2916620  NOT1210LH8B       blood
4   GSM2916622  NOT1213LH2B       blood
..         ...          ...         ...
87  GSM2916802       140438       blood
88  GSM2916809       141270       blood
89  GSM2916810       141271       blood
90  GSM2916811       141272       blood
91  GSM2916812       141273       blood

[92 rows x 3 columns]

Endometrium samples: 110
Blood samples: 92

In [10]:
model_data = pd.read_csv(r"F:\downloads microsodt\GSE108966_RIF_ml_dataset.csv") 
display(model_data.head(3))
print(model_data.shape)

print(model_data['Condition'].value_counts())
print(model_data['Tissue'].value_counts())

,Sample,GSM_ID,Tissue,Patient_ID,LH_Day,Condition,hsa-let-7a-3p,hsa-let-7a-5p,hsa-let-7a-2-3p,hsa-let-7b-5p,...,hsa-miR-95-5p,hsa-miR-95-3p,hsa-miR-96-5p,hsa-miR-96-3p,hsa-miR-98-3p,hsa-miR-98-5p,hsa-miR-99a-3p,hsa-miR-99a-5p,hsa-miR-99b-5p,hsa-miR-99b-3p
0,13586,GSM2916723,endometrium,8,2,CONTROL,289,775079,2,89304,...,14,329,1150,0,34,37013,1034,17456,31791,552
1,13590,GSM2916724,endometrium,8,8,CONTROL,525,182340,2,31151,...,6,115,283,1,39,7448,236,3941,4653,184
2,13606,GSM2916725,blood,8,2,CONTROL,47,20735,0,1003,...,0,3,0,0,38,1164,2,10,902,16

(91, 2594)
Condition
CONTROL    62
IVF        29
Name: count, dtype: int64
Tissue
endometrium    46
blood          45
Name: count, dtype: int64

In [13]:
[x for x in model_data.columns if "3607" in str(x)]

['hsa-miR-3607-3p', 'hsa-miR-3607-5p']

In [11]:
print(model_data.columns.tolist())
metadata_cols = [
    'Sample',
    'GSM_ID',
    'Tissue',
    'Patient_ID',
    'LH_Day',
    'Condition',
]


model_data_metadata = model_data[metadata_cols]

display(model_data_metadata)

['Sample', 'GSM_ID', 'Tissue', 'Patient_ID', 'LH_Day', 'Condition', 'hsa-let-7a-3p', 'hsa-let-7a-5p', 'hsa-let-7a-2-3p', 'hsa-let-7b-5p', 'hsa-let-7b-3p', 'hsa-let-7c-3p', 'hsa-let-7c-5p', 'hsa-let-7d-3p', 'hsa-let-7d-5p', 'hsa-let-7e-3p', 'hsa-let-7e-5p', 'hsa-let-7f-5p', 'hsa-let-7f-1-3p', 'hsa-let-7f-2-3p', 'hsa-let-7g-5p', 'hsa-let-7g-3p', 'hsa-let-7i-3p', 'hsa-let-7i-5p', 'hsa-miR-1-3p', 'hsa-miR-1-5p', 'hsa-miR-100-3p', 'hsa-miR-100-5p', 'hsa-miR-101-5p', 'hsa-miR-101-3p', 'hsa-miR-103a-3p', 'hsa-miR-103a-2-5p', 'hsa-miR-103b', 'hsa-miR-105-3p', 'hsa-miR-105-5p', 'hsa-miR-106a-3p', 'hsa-miR-106a-5p', 'hsa-miR-106b-5p', 'hsa-miR-106b-3p', 'hsa-miR-107', 'hsa-miR-10a-5p', 'hsa-miR-10a-3p', 'hsa-miR-10b-5p', 'hsa-miR-10b-3p', 'hsa-miR-1178-3p', 'hsa-miR-1178-5p', 'hsa-miR-1179', 'hsa-miR-1180-5p', 'hsa-miR-1180-3p', 'hsa-miR-1181', 'hsa-miR-1182', 'hsa-miR-1183', 'hsa-miR-1184', 'hsa-miR-1185-5p', 'hsa-miR-1185-1-3p', 'hsa-miR-1185-2-3p', 'hsa-miR-1193', 'hsa-miR-1197', 'hsa-miR-1199-5p', 'hsa-miR-1199-3p', 'hsa-miR-1200', 'hsa-miR-1202', 'hsa-miR-1203', 'hsa-miR-1204', 'hsa-miR-1205', 'hsa-miR-1206', 'hsa-miR-1207-5p', 'hsa-miR-1207-3p', 'hsa-miR-1208', 'hsa-miR-1224-5p', 'hsa-miR-1224-3p', 'hsa-miR-1225-3p', 'hsa-miR-1225-5p', 'hsa-miR-1226-3p', 'hsa-miR-1226-5p', 'hsa-miR-1227-3p', 'hsa-miR-1227-5p', 'hsa-miR-1228-3p', 'hsa-miR-1228-5p', 'hsa-miR-1229-3p', 'hsa-miR-1229-5p', 'hsa-miR-122-3p', 'hsa-miR-122-5p', 'hsa-miR-1231', 'hsa-miR-1233-5p', 'hsa-miR-1233-3p', 'hsa-miR-1234-3p', 'hsa-miR-1236-5p', 'hsa-miR-1236-3p', 'hsa-miR-1237-5p', 'hsa-miR-1237-3p', 'hsa-miR-1238-5p', 'hsa-miR-1238-3p', 'hsa-miR-124-5p', 'hsa-miR-124-3p', 'hsa-miR-1243', 'hsa-miR-1244', 'hsa-miR-1245a', 'hsa-miR-1245b-5p', 'hsa-miR-1245b-3p', 'hsa-miR-1246', 'hsa-miR-1247-3p', 'hsa-miR-1247-5p', 'hsa-miR-1248', 'hsa-miR-1249-5p', 'hsa-miR-1249-3p', 'hsa-miR-1250-5p', 'hsa-miR-1250-3p', 'hsa-miR-1251-5p', 'hsa-miR-1251-3p', 'hsa-miR-1252-3p', 'hsa-miR-1252-5p', 'hsa-miR-1253', 'hsa-miR-1254', 'hsa-miR-1255a', 'hsa-miR-1255b-5p', 'hsa-miR-1255b-2-3p', 'hsa-miR-1256', 'hsa-miR-1257', 'hsa-miR-1258', 'hsa-miR-125a-5p', 'hsa-miR-125a-3p', 'hsa-miR-125b-5p', 'hsa-miR-125b-1-3p', 'hsa-miR-125b-2-3p', 'hsa-miR-1260a', 'hsa-miR-1260b', 'hsa-miR-1261', 'hsa-miR-1262', 'hsa-miR-1263', 'hsa-miR-1264', 'hsa-miR-1265', 'hsa-miR-1266-3p', 'hsa-miR-1266-5p', 'hsa-miR-1267', 'hsa-miR-1268a', 'hsa-miR-1268b', 'hsa-miR-1269a', 'hsa-miR-1269b', 'hsa-miR-126-5p', 'hsa-miR-126-3p', 'hsa-miR-1270', 'hsa-miR-1271-3p', 'hsa-miR-1271-5p', 'hsa-miR-1272', 'hsa-miR-1273a', 'hsa-miR-1273c', 'hsa-miR-1273d', 'hsa-miR-1273e', 'hsa-miR-1273f', 'hsa-miR-1273g-3p', 'hsa-miR-1273g-5p', 'hsa-miR-1273h-5p', 'hsa-miR-1273h-3p', 'hsa-miR-1275', 'hsa-miR-1276', 'hsa-miR-1277-5p', 'hsa-miR-1277-3p', 'hsa-miR-1278', 'hsa-miR-1279', 'hsa-miR-127-3p', 'hsa-miR-127-5p', 'hsa-miR-128-1-5p', 'hsa-miR-128-3p', 'hsa-miR-128-2-5p', 'hsa-miR-1281', 'hsa-miR-1282', 'hsa-miR-1283', 'hsa-miR-1284', 'hsa-miR-1285-3p', 'hsa-miR-1285-5p', 'hsa-miR-1286', 'hsa-miR-1287-5p', 'hsa-miR-1287-3p', 'hsa-miR-1288-5p', 'hsa-miR-1288-3p', 'hsa-miR-1289', 'hsa-miR-129-1-3p', 'hsa-miR-129-5p', 'hsa-miR-129-2-3p', 'hsa-miR-1290', 'hsa-miR-1291', 'hsa-miR-1292-3p', 'hsa-miR-1292-5p', 'hsa-miR-1293', 'hsa-miR-1294', 'hsa-miR-1295a', 'hsa-miR-1295b-5p', 'hsa-miR-1295b-3p', 'hsa-miR-1296-5p', 'hsa-miR-1296-3p', 'hsa-miR-1297', 'hsa-miR-1298-5p', 'hsa-miR-1298-3p', 'hsa-miR-1299', 'hsa-miR-1301-5p', 'hsa-miR-1301-3p', 'hsa-miR-1302', 'hsa-miR-1303', 'hsa-miR-1304-3p', 'hsa-miR-1304-5p', 'hsa-miR-1305', 'hsa-miR-1306-5p', 'hsa-miR-1306-3p', 'hsa-miR-1307-5p', 'hsa-miR-1307-3p', 'hsa-miR-130a-5p', 'hsa-miR-130a-3p', 'hsa-miR-130b-5p', 'hsa-miR-130b-3p', 'hsa-miR-1321', 'hsa-miR-1322', 'hsa-miR-1323', 'hsa-miR-1324', 'hsa-miR-132-3p', 'hsa-miR-132-5p', 'hsa-miR-133a-3p', 'hsa-miR-133a-5p', 'hsa-miR-133b', 'hsa-miR-1343-5p', 'hsa-miR-1343-3p', 'hsa-miR-134-5p', 'hsa-miR-134-3p', 'hsa-miR-135a-5p', 'hsa-miR-135a-3p', 'hsa-miR-135b-3p', 'hsa-miR-135b-5p', 'hsa-miR-136-3p', 'hsa-miR-136-5p', 'hsa-miR-137', 'hsa-miR-138-5p', 'hsa-miR-138-1-3p', 'hsa-miR-138-2-3p', 'hsa-miR-139-3p', 'hsa-miR-139-5p', 'hsa-miR-140-5p', 'hsa-miR-140-3p', 'hsa-miR-141-5p', 'hsa-miR-141-3p', 'hsa-miR-142-5p', 'hsa-miR-142-3p', 'hsa-miR-143-3p', 'hsa-miR-143-5p', 'hsa-miR-144-3p', 'hsa-miR-144-5p', 'hsa-miR-145-5p', 'hsa-miR-145-3p', 'hsa-miR-1468-5p', 'hsa-miR-1468-3p', 'hsa-miR-1469', 'hsa-miR-146a-5p', 'hsa-miR-146a-3p', 'hsa-miR-146b-3p', 'hsa-miR-146b-5p', 'hsa-miR-1470', 'hsa-miR-1471', 'hsa-miR-147a', 'hsa-miR-147b', 'hsa-miR-148a-3p', 'hsa-miR-148a-5p', 'hsa-miR-148b-5p', 'hsa-miR-148b-3p', 'hsa-miR-149-5p', 'hsa-miR-149-3p', 'hsa-miR-150-5p', 'hsa-miR-150-3p', 'hsa-miR-151b', 'hsa-miR-151a-5p', 'hsa-miR-151a-3p', 'hsa-miR-152-5p', 'hsa-miR-152-3p', 'hsa-miR-153-3p', 'hsa-miR-153-5p', 'hsa-miR-1537-5p', 'hsa-miR-1537-3p', 'hsa-miR-1538', 'hsa-miR-1539', 'hsa-miR-154-5p', 'hsa-miR-154-3p', 'hsa-miR-155-5p', 'hsa-miR-155-3p', 'hsa-miR-1587', 'hsa-miR-15a-5p', 'hsa-miR-15a-3p', 'hsa-miR-15b-3p', 'hsa-miR-15b-5p', 'hsa-miR-16-1-3p', 'hsa-miR-16-5p', 'hsa-miR-16-2-3p', 'hsa-miR-17-5p', 'hsa-miR-17-3p', 'hsa-miR-181a-3p', 'hsa-miR-181a-5p', 'hsa-miR-181a-2-3p', 'hsa-miR-181b-3p', 'hsa-miR-181b-5p', 'hsa-miR-181b-2-3p', 'hsa-miR-181c-3p', 'hsa-miR-181c-5p', 'hsa-miR-181d-3p', 'hsa-miR-181d-5p', 'hsa-miR-1825', 'hsa-miR-1827', 'hsa-miR-182-3p', 'hsa-miR-182-5p', 'hsa-miR-183-3p', 'hsa-miR-183-5p', 'hsa-miR-184', 'hsa-miR-185-5p', 'hsa-miR-185-3p', 'hsa-miR-186-5p', 'hsa-miR-186-3p', 'hsa-miR-187-3p', 'hsa-miR-187-5p', 'hsa-miR-188-5p', 'hsa-miR-188-3p', 'hsa-miR-18a-5p', 'hsa-miR-18a-3p', 'hsa-miR-18b-5p', 'hsa-miR-18b-3p', 'hsa-miR-1908-5p', 'hsa-miR-1908-3p', 'hsa-miR-1909-3p', 'hsa-miR-1909-5p', 'hsa-miR-190a-5p', 'hsa-miR-190a-3p', 'hsa-miR-190b', 'hsa-miR-1910-3p', 'hsa-miR-1910-5p', 'hsa-miR-1911-5p', 'hsa-miR-1911-3p', 'hsa-miR-1912', 'hsa-miR-1913', 'hsa-miR-1914-5p', 'hsa-miR-1914-3p', 'hsa-miR-1915-3p', 'hsa-miR-1915-5p', 'hsa-miR-191-3p', 'hsa-miR-191-5p', 'hsa-miR-192-3p', 'hsa-miR-192-5p', 'hsa-miR-193a-3p', 'hsa-miR-193a-5p', 'hsa-miR-193b-3p', 'hsa-miR-193b-5p', 'hsa-miR-194-5p', 'hsa-miR-194-3p', 'hsa-miR-195-3p', 'hsa-miR-195-5p', 'hsa-miR-196a-5p', 'hsa-miR-196a-3p', 'hsa-miR-196b-5p', 'hsa-miR-196b-3p', 'hsa-miR-1972', 'hsa-miR-1973', 'hsa-miR-1976', 'hsa-miR-197-5p', 'hsa-miR-197-3p', 'hsa-miR-198', 'hsa-miR-199a-3p', 'hsa-miR-199a-5p', 'hsa-miR-199b-3p', 'hsa-miR-199b-5p', 'hsa-miR-19a-3p', 'hsa-miR-19a-5p', 'hsa-miR-19b-1-5p', 'hsa-miR-19b-3p', 'hsa-miR-19b-2-5p', 'hsa-miR-200a-3p', 'hsa-miR-200a-5p', 'hsa-miR-200b-3p', 'hsa-miR-200b-5p', 'hsa-miR-200c-3p', 'hsa-miR-200c-5p', 'hsa-miR-202-3p', 'hsa-miR-202-5p', 'hsa-miR-203a-5p', 'hsa-miR-203a-3p', 'hsa-miR-203b-5p', 'hsa-miR-203b-3p', 'hsa-miR-204-5p', 'hsa-miR-204-3p', 'hsa-miR-2052', 'hsa-miR-2053', 'hsa-miR-2054', 'hsa-miR-205-3p', 'hsa-miR-205-5p', 'hsa-miR-206', 'hsa-miR-208a-5p', 'hsa-miR-208a-3p', 'hsa-miR-208b-5p', 'hsa-miR-208b-3p', 'hsa-miR-20a-3p', 'hsa-miR-20a-5p', 'hsa-miR-20b-5p', 'hsa-miR-20b-3p', 'hsa-miR-210-3p', 'hsa-miR-210-5p', 'hsa-miR-2110', 'hsa-miR-2113', 'hsa-miR-2114-5p', 'hsa-miR-2114-3p', 'hsa-miR-2115-3p', 'hsa-miR-2115-5p', 'hsa-miR-2116-5p', 'hsa-miR-2116-3p', 'hsa-miR-2117', 'hsa-miR-211-3p', 'hsa-miR-211-5p', 'hsa-miR-212-3p', 'hsa-miR-212-5p', 'hsa-miR-214-5p', 'hsa-miR-214-3p', 'hsa-miR-215-3p', 'hsa-miR-215-5p', 'hsa-miR-216a-5p', 'hsa-miR-216a-3p', 'hsa-miR-216b-3p', 'hsa-miR-216b-5p', 'hsa-miR-217', 'hsa-miR-218-5p', 'hsa-miR-218-1-3p', 'hsa-miR-218-2-3p', 'hsa-miR-219a-5p', 'hsa-miR-219a-1-3p', 'hsa-miR-219a-2-3p', 'hsa-miR-219b-5p', 'hsa-miR-219b-3p', 'hsa-miR-21-5p', 'hsa-miR-21-3p', 'hsa-miR-221-3p', 'hsa-miR-221-5p', 'hsa-miR-222-5p', 'hsa-miR-222-3p', 'hsa-miR-223-3p', 'hsa-miR-223-5p', 'hsa-miR-224-5p', 'hsa-miR-224-3p', 'hsa-miR-2276-3p', 'hsa-miR-2276-5p', 'hsa-miR-2277-3p', 'hsa-miR-2277-5p', 'hsa-miR-2278', 'hsa-miR-22-3p', 'hsa-miR-22-5p', 'hsa-miR-2355-5p', 'hsa-miR-2355-3p', 'hsa-miR-2392', 'hsa-miR-23a-3p', 'hsa-miR-23a-5p', 'hsa-miR-23b-3p', 'hsa-miR-23b-5p', 'hsa-miR-23c', 'hsa-miR-24-1-5p', 'hsa-miR-24-3p', 'hsa-miR-24-2-5p', 'hsa-miR-2467-5p', 'hsa-miR-2467-3p', 'hsa-miR-25-5p', 'hsa-miR-25-3p', 'hsa-miR-2681-5p', 'hsa-miR-2681-3p', 'hsa-miR-2682-3p', 'hsa-miR-2682-5p', 'hsa-miR-26a-5p', 'hsa-miR-26a-1-3p', 'hsa-miR-26a-2-3p', 'hsa-miR-26b-5p', 'hsa-miR-26b-3p', 'hsa-miR-27a-5p', 'hsa-miR-27a-3p', 'hsa-miR-27b-5p', 'hsa-miR-27b-3p', 'hsa-miR-2861', 'hsa-miR-28-3p', 'hsa-miR-28-5p', 'hsa-miR-2909', 'hsa-miR-296-5p', 'hsa-miR-296-3p', 'hsa-miR-297', 'hsa-miR-298', 'hsa-miR-299-5p', 'hsa-miR-299-3p', 'hsa-miR-29a-5p', 'hsa-miR-29a-3p', 'hsa-miR-29b-1-5p', 'hsa-miR-29b-3p', 'hsa-miR-29b-2-5p', 'hsa-miR-29c-3p', 'hsa-miR-29c-5p', 'hsa-miR-300', 'hsa-miR-301a-5p', 'hsa-miR-301a-3p', 'hsa-miR-301b-5p', 'hsa-miR-301b-3p', 'hsa-miR-302a-3p', 'hsa-miR-302a-5p', 'hsa-miR-302b-5p', 'hsa-miR-302b-3p', 'hsa-miR-302c-5p', 'hsa-miR-302c-3p', 'hsa-miR-302d-3p', 'hsa-miR-302d-5p', 'hsa-miR-302e', 'hsa-miR-302f', 'hsa-miR-3064-5p', 'hsa-miR-3064-3p', 'hsa-miR-3065-3p', 'hsa-miR-3065-5p', 'hsa-miR-3074-5p', 'hsa-miR-3074-3p', 'hsa-miR-30a-5p', 'hsa-miR-30a-3p', 'hsa-miR-30b-5p', 'hsa-miR-30b-3p', 'hsa-miR-30c-5p', 'hsa-miR-30c-1-3p', 'hsa-miR-30c-2-3p', 'hsa-miR-30d-3p', 'hsa-miR-30d-5p', 'hsa-miR-30e-3p', 'hsa-miR-30e-5p', 'hsa-miR-3115', 'hsa-miR-3116', 'hsa-miR-3117-5p', 'hsa-miR-3117-3p', 'hsa-miR-3118', 'hsa-miR-3119', 'hsa-miR-3120-3p', 'hsa-miR-3120-5p', 'hsa-miR-3121-3p', 'hsa-miR-3121-5p', 'hsa-miR-3122', 'hsa-miR-3123', 'hsa-miR-3124-5p', 'hsa-miR-3124-3p', 'hsa-miR-3125', 'hsa-miR-3126-5p', 'hsa-miR-3126-3p', 'hsa-miR-3127-5p', 'hsa-miR-3127-3p', 'hsa-miR-3128', 'hsa-miR-3129-5p', 'hsa-miR-3129-3p', 'hsa-miR-3130-3p', 'hsa-miR-3130-5p', 'hsa-miR-3131', 'hsa-miR-3132', 'hsa-miR-3133', 'hsa-miR-3134', 'hsa-miR-3135a', 'hsa-miR-3135b', 'hsa-miR-3136-5p', 'hsa-miR-3136-3p', 'hsa-miR-3137', 'hsa-miR-3138', 'hsa-miR-3139', 'hsa-miR-3140-5p', 'hsa-miR-3140-3p', 'hsa-miR-3141', 'hsa-miR-3142', 'hsa-miR-3143', 'hsa-miR-3144-5p', 'hsa-miR-3144-3p', 'hsa-miR-3145-5p', 'hsa-miR-3145-3p', 'hsa-miR-3146', 'hsa-miR-3147', 'hsa-miR-3148', 'hsa-miR-3149', 'hsa-miR-3150a-5p', 'hsa-miR-3150a-3p', 'hsa-miR-3150b-3p', 'hsa-miR-3150b-5p', 'hsa-miR-3151-3p', 'hsa-miR-3151-5p', 'hsa-miR-3152-5p', 'hsa-miR-3152-3p', 'hsa-miR-3153', 'hsa-miR-3154', 'hsa-miR-3155a', 'hsa-miR-3155b', 'hsa-miR-3156-5p', 'hsa-miR-3156-3p', 'hsa-miR-3157-3p', 'hsa-miR-3157-5p', 'hsa-miR-3158-3p', 'hsa-miR-3158-5p', 'hsa-miR-3159', 'hsa-miR-3160-3p', 'hsa-miR-3160-5p', 'hsa-miR-3161', 'hsa-miR-3162-3p', 'hsa-miR-3162-5p', 'hsa-miR-3163', 'hsa-miR-3164', 'hsa-miR-3165', 'hsa-miR-3166', 'hsa-miR-3167', 'hsa-miR-3168', 'hsa-miR-3169', 'hsa-miR-3170', 'hsa-miR-3171', 'hsa-miR-3173-5p', 'hsa-miR-3173-3p', 'hsa-miR-3174', 'hsa-miR-3175', 'hsa-miR-3176', 'hsa-miR-3177-3p', 'hsa-miR-3177-5p', 'hsa-miR-3178', 'hsa-miR-3179', 'hsa-miR-3180-3p', 'hsa-miR-3180', 'hsa-miR-3180-5p', 'hsa-miR-3181', 'hsa-miR-3182', 'hsa-miR-3183', 'hsa-miR-3184-3p', 'hsa-miR-3184-5p', 'hsa-miR-3185', 'hsa-miR-3186-5p', 'hsa-miR-3186-3p', 'hsa-miR-3187-5p', 'hsa-miR-3187-3p', 'hsa-miR-3188', 'hsa-miR-3189-3p', 'hsa-miR-3189-5p', 'hsa-miR-3190-5p', 'hsa-miR-3190-3p', 'hsa-miR-3191-3p', 'hsa-miR-3191-5p', 'hsa-miR-3192-3p', 'hsa-miR-3192-5p', 'hsa-miR-3193', 'hsa-miR-3194-3p', 'hsa-miR-3194-5p', 'hsa-miR-3195', 'hsa-miR-3196', 'hsa-miR-3197', 'hsa-miR-3198', 'hsa-miR-3199', 'hsa-miR-31-5p', 'hsa-miR-31-3p', 'hsa-miR-3200-5p', 'hsa-miR-3200-3p', 'hsa-miR-3201', 'hsa-miR-3202', 'hsa-miR-320a', 'hsa-miR-320b', 'hsa-miR-320c', 'hsa-miR-320d', 'hsa-miR-320e', 'hsa-miR-323a-5p', 'hsa-miR-323a-3p', 'hsa-miR-323b-5p', 'hsa-miR-323b-3p', 'hsa-miR-324-3p', 'hsa-miR-324-5p', 'hsa-miR-325', 'hsa-miR-326', 'hsa-miR-328-3p', 'hsa-miR-328-5p', 'hsa-miR-329-5p', 'hsa-miR-329-3p', 'hsa-miR-32-5p', 'hsa-miR-32-3p', 'hsa-miR-330-3p', 'hsa-miR-330-5p', 'hsa-miR-331-3p', 'hsa-miR-331-5p', 'hsa-miR-335-3p', 'hsa-miR-335-5p', 'hsa-miR-337-5p', 'hsa-miR-337-3p', 'hsa-miR-338-5p', 'hsa-miR-338-3p', 'hsa-miR-339-5p', 'hsa-miR-339-3p', 'hsa-miR-33a-5p', 'hsa-miR-33a-3p', 'hsa-miR-33b-3p', 'hsa-miR-33b-5p', 'hsa-miR-340-3p', 'hsa-miR-340-5p', 'hsa-miR-342-3p', 'hsa-miR-342-5p', 'hsa-miR-345-5p', 'hsa-miR-345-3p', 'hsa-miR-346', 'hsa-miR-34a-5p', 'hsa-miR-34a-3p', 'hsa-miR-34b-3p', 'hsa-miR-34b-5p', 'hsa-miR-34c-3p', 'hsa-miR-34c-5p', 'hsa-miR-3529-5p', 'hsa-miR-3529-3p', 'hsa-miR-3591-5p', 'hsa-miR-3591-3p', 'hsa-miR-3605-5p', 'hsa-miR-3605-3p', 'hsa-miR-3606-3p', 'hsa-miR-3606-5p', 'hsa-miR-3607-3p', 'hsa-miR-3607-5p', 'hsa-miR-3609', 'hsa-miR-3610', 'hsa-miR-3611', 'hsa-miR-3612', 'hsa-miR-3613-5p', 'hsa-miR-3613-3p', 'hsa-miR-3614-5p', 'hsa-miR-3614-3p', 'hsa-miR-3615', 'hsa-miR-3616-3p', 'hsa-miR-3616-5p', 'hsa-miR-3617-3p', 'hsa-miR-3617-5p', 'hsa-miR-3618', 'hsa-miR-3619-5p', 'hsa-miR-3619-3p', 'hsa-miR-361-3p', 'hsa-miR-361-5p', 'hsa-miR-3620-5p', 'hsa-miR-3620-3p', 'hsa-miR-3621', 'hsa-miR-3622a-5p', 'hsa-miR-3622a-3p', 'hsa-miR-3622b-3p', 'hsa-miR-3622b-5p', 'hsa-miR-362-3p', 'hsa-miR-362-5p', 'hsa-miR-363-5p', 'hsa-miR-363-3p', 'hsa-miR-3646', 'hsa-miR-3648', 'hsa-miR-3649', 'hsa-miR-3650', 'hsa-miR-3651', 'hsa-miR-3652', 'hsa-miR-3653-3p', 'hsa-miR-3653-5p', 'hsa-miR-3654', 'hsa-miR-3655', 'hsa-miR-3656', 'hsa-miR-3657', 'hsa-miR-3658', 'hsa-miR-3659', 'hsa-miR-365b-3p', 'hsa-miR-365a-3p', 'hsa-miR-365a-5p', 'hsa-miR-365b-5p', 'hsa-miR-3660', 'hsa-miR-3661', 'hsa-miR-3662', 'hsa-miR-3663-5p', 'hsa-miR-3663-3p', 'hsa-miR-3664-3p', 'hsa-miR-3664-5p', 'hsa-miR-3665', 'hsa-miR-3666', 'hsa-miR-3667-5p', 'hsa-miR-3667-3p', 'hsa-miR-3668', 'hsa-miR-3670', 'hsa-miR-3671', 'hsa-miR-3672', 'hsa-miR-3674', 'hsa-miR-3675-3p', 'hsa-miR-3675-5p', 'hsa-miR-3677-3p', 'hsa-miR-3677-5p', 'hsa-miR-3678-3p', 'hsa-miR-3678-5p', 'hsa-miR-3679-5p', 'hsa-miR-3679-3p', 'hsa-miR-367-5p', 'hsa-miR-367-3p', 'hsa-miR-3680-3p', 'hsa-miR-3680-5p', 'hsa-miR-3681-5p', 'hsa-miR-3681-3p', 'hsa-miR-3682-5p', 'hsa-miR-3682-3p', 'hsa-miR-3683', 'hsa-miR-3684', 'hsa-miR-3685', 'hsa-miR-3686', 'hsa-miR-3687', 'hsa-miR-3688-5p', 'hsa-miR-3688-3p', 'hsa-miR-3689a-5p', 'hsa-miR-3689e', 'hsa-miR-3689a-3p', 'hsa-miR-3689b-5p', 'hsa-miR-3689b-3p', 'hsa-miR-3689c', 'hsa-miR-3689d', 'hsa-miR-3689f', 'hsa-miR-3690', 'hsa-miR-3691-5p', 'hsa-miR-3691-3p', 'hsa-miR-3692-3p', 'hsa-miR-3692-5p', 'hsa-miR-369-5p', 'hsa-miR-369-3p', 'hsa-miR-370-3p', 'hsa-miR-370-5p', 'hsa-miR-3713', 'hsa-miR-3714', 'hsa-miR-371a-3p', 'hsa-miR-371a-5p', 'hsa-miR-371b-3p', 'hsa-miR-371b-5p', 'hsa-miR-372-3p', 'hsa-miR-372-5p', 'hsa-miR-373-5p', 'hsa-miR-373-3p', 'hsa-miR-374a-3p', 'hsa-miR-374a-5p', 'hsa-miR-374b-3p', 'hsa-miR-374b-5p', 'hsa-miR-374c-3p', 'hsa-miR-374c-5p', 'hsa-miR-375', 'hsa-miR-376a-5p', 'hsa-miR-376a-3p', 'hsa-miR-376a-2-5p', 'hsa-miR-376b-3p', 'hsa-miR-376b-5p', 'hsa-miR-376c-3p', 'hsa-miR-376c-5p', 'hsa-miR-377-5p', 'hsa-miR-377-3p', 'hsa-miR-378a-5p', 'hsa-miR-378a-3p', 'hsa-miR-378b', 'hsa-miR-378c', 'hsa-miR-378d', 'hsa-miR-378e', 'hsa-miR-378f', 'hsa-miR-378g', 'hsa-miR-378h', 'hsa-miR-378i', 'hsa-miR-378j', 'hsa-miR-379-5p', 'hsa-miR-379-3p', 'hsa-miR-380-3p', 'hsa-miR-380-5p', 'hsa-miR-381-3p', 'hsa-miR-381-5p', 'hsa-miR-382-3p', 'hsa-miR-382-5p', 'hsa-miR-383-3p', 'hsa-miR-383-5p', 'hsa-miR-384', 'hsa-miR-3907', 'hsa-miR-3908', 'hsa-miR-3909', 'hsa-miR-3910', 'hsa-miR-3911', 'hsa-miR-3912-3p', 'hsa-miR-3912-5p', 'hsa-miR-3913-5p', 'hsa-miR-3913-3p', 'hsa-miR-3914', 'hsa-miR-3915', 'hsa-miR-3916', 'hsa-miR-3917', 'hsa-miR-3918', 'hsa-miR-3919', 'hsa-miR-3920', 'hsa-miR-3921', 'hsa-miR-3922-5p', 'hsa-miR-3922-3p', 'hsa-miR-3923', 'hsa-miR-3924', 'hsa-miR-3925-3p', 'hsa-miR-3925-5p', 'hsa-miR-3926', 'hsa-miR-3927-5p', 'hsa-miR-3927-3p', 'hsa-miR-3928-3p', 'hsa-miR-3928-5p', 'hsa-miR-3929', 'hsa-miR-3934-5p', 'hsa-miR-3934-3p', 'hsa-miR-3935', 'hsa-miR-3936', 'hsa-miR-3937', 'hsa-miR-3938', 'hsa-miR-3939', 'hsa-miR-3940-5p', 'hsa-miR-3940-3p', 'hsa-miR-3941', 'hsa-miR-3942-3p', 'hsa-miR-3942-5p', 'hsa-miR-3943', 'hsa-miR-3944-5p', 'hsa-miR-3944-3p', 'hsa-miR-3945', 'hsa-miR-3960', 'hsa-miR-3972', 'hsa-miR-3973', 'hsa-miR-3974', 'hsa-miR-3975', 'hsa-miR-3976', 'hsa-miR-3977', 'hsa-miR-3978', 'hsa-miR-409-5p', 'hsa-miR-409-3p', 'hsa-miR-410-3p', 'hsa-miR-410-5p', 'hsa-miR-411-5p', 'hsa-miR-411-3p', 'hsa-miR-412-5p', 'hsa-miR-412-3p', 'hsa-miR-421', 'hsa-miR-422a', 'hsa-miR-423-5p', 'hsa-miR-423-3p', 'hsa-miR-424-3p', 'hsa-miR-424-5p', 'hsa-miR-4251', 'hsa-miR-4252', 'hsa-miR-4253', 'hsa-miR-4254', 'hsa-miR-4255', 'hsa-miR-4256', 'hsa-miR-4257', 'hsa-miR-4258', 'hsa-miR-4259', 'hsa-miR-425-3p', 'hsa-miR-425-5p', 'hsa-miR-4260', 'hsa-miR-4261', 'hsa-miR-4262', 'hsa-miR-4263', 'hsa-miR-4264', 'hsa-miR-4265', 'hsa-miR-4266', 'hsa-miR-4267', 'hsa-miR-4268', 'hsa-miR-4269', 'hsa-miR-4270', 'hsa-miR-4271', 'hsa-miR-4272', 'hsa-miR-4273', 'hsa-miR-4274', 'hsa-miR-4275', 'hsa-miR-4276', 'hsa-miR-4277', 'hsa-miR-4278', 'hsa-miR-4279', 'hsa-miR-4280', 'hsa-miR-4281', 'hsa-miR-4282', 'hsa-miR-4283', 'hsa-miR-4284', 'hsa-miR-4285', 'hsa-miR-4286', 'hsa-miR-4287', 'hsa-miR-4288', 'hsa-miR-4289', 'hsa-miR-4290', 'hsa-miR-4291', 'hsa-miR-4292', 'hsa-miR-4293', 'hsa-miR-4294', 'hsa-miR-4295', 'hsa-miR-4296', 'hsa-miR-4297', 'hsa-miR-4298', 'hsa-miR-4299', 'hsa-miR-429', 'hsa-miR-4300', 'hsa-miR-4301', 'hsa-miR-4302', 'hsa-miR-4303', 'hsa-miR-4304', 'hsa-miR-4305', 'hsa-miR-4306', 'hsa-miR-4307', 'hsa-miR-4308', 'hsa-miR-4309', 'hsa-miR-4310', 'hsa-miR-4311', 'hsa-miR-4312', 'hsa-miR-4313', 'hsa-miR-4314', 'hsa-miR-4315', 'hsa-miR-4316', 'hsa-miR-4317', 'hsa-miR-4318', 'hsa-miR-4319', 'hsa-miR-431-3p', 'hsa-miR-431-5p', 'hsa-miR-4320', 'hsa-miR-4321', 'hsa-miR-4322', 'hsa-miR-4323', 'hsa-miR-4324', 'hsa-miR-4325', 'hsa-miR-4326', 'hsa-miR-4327', 'hsa-miR-4328', 'hsa-miR-4329', 'hsa-miR-432-3p', 'hsa-miR-432-5p', 'hsa-miR-4330', 'hsa-miR-433-3p', 'hsa-miR-433-5p', 'hsa-miR-4417', 'hsa-miR-4418', 'hsa-miR-4419a', 'hsa-miR-4419b', 'hsa-miR-4420', 'hsa-miR-4421', 'hsa-miR-4422', 'hsa-miR-4423-5p', 'hsa-miR-4423-3p', 'hsa-miR-4424', 'hsa-miR-4425', 'hsa-miR-4426', 'hsa-miR-4427', 'hsa-miR-4428', 'hsa-miR-4429', 'hsa-miR-4430', 'hsa-miR-4431', 'hsa-miR-4432', 'hsa-miR-4433a-5p', 'hsa-miR-4433a-3p', 'hsa-miR-4433b-5p', 'hsa-miR-4433b-3p', 'hsa-miR-4434', 'hsa-miR-4435', 'hsa-miR-4436a', 'hsa-miR-4436b-3p', 'hsa-miR-4436b-5p', 'hsa-miR-4437', 'hsa-miR-4438', 'hsa-miR-4439', 'hsa-miR-4440', 'hsa-miR-4441', 'hsa-miR-4442', 'hsa-miR-4443', 'hsa-miR-4444', 'hsa-miR-4445-3p', 'hsa-miR-4445-5p', 'hsa-miR-4446-5p', 'hsa-miR-4446-3p', 'hsa-miR-4447', 'hsa-miR-4448', 'hsa-miR-4449', 'hsa-miR-4450', 'hsa-miR-4451', 'hsa-miR-4452', 'hsa-miR-4453', 'hsa-miR-4454', 'hsa-miR-4455', 'hsa-miR-4456', 'hsa-miR-4457', 'hsa-miR-4458', 'hsa-miR-4459', 'hsa-miR-4460', 'hsa-miR-4461', 'hsa-miR-4462', 'hsa-miR-4463', 'hsa-miR-4464', 'hsa-miR-4465', 'hsa-miR-4466', 'hsa-miR-4467', 'hsa-miR-4468', 'hsa-miR-4469', 'hsa-miR-4470', 'hsa-miR-4471', 'hsa-miR-4472', 'hsa-miR-4473', 'hsa-miR-4474-3p', 'hsa-miR-4474-5p', 'hsa-miR-4475', 'hsa-miR-4476', 'hsa-miR-4477a', 'hsa-miR-4477b', 'hsa-miR-4478', 'hsa-miR-4479', 'hsa-miR-4480', 'hsa-miR-4481', 'hsa-miR-4482-5p', 'hsa-miR-4482-3p', 'hsa-miR-4483', 'hsa-miR-4484', 'hsa-miR-4485-5p', 'hsa-miR-4485-3p', 'hsa-miR-4486', 'hsa-miR-4487', 'hsa-miR-4488', 'hsa-miR-4489', 'hsa-miR-448', 'hsa-miR-4490', 'hsa-miR-4491', 'hsa-miR-4492', 'hsa-miR-4493', 'hsa-miR-4494', 'hsa-miR-4495', 'hsa-miR-4496', 'hsa-miR-4497', 'hsa-miR-4498', 'hsa-miR-4499', 'hsa-miR-449a', 'hsa-miR-449b-3p', 'hsa-miR-449b-5p', 'hsa-miR-449c-5p', 'hsa-miR-449c-3p', 'hsa-miR-4500', 'hsa-miR-4501', 'hsa-miR-4502', 'hsa-miR-4503', 'hsa-miR-4504', 'hsa-miR-4505', 'hsa-miR-4506', 'hsa-miR-4507', 'hsa-miR-4508', 'hsa-miR-4509', 'hsa-miR-450a-1-3p', 'hsa-miR-450a-5p', 'hsa-miR-450a-2-3p', 'hsa-miR-450b-3p', 'hsa-miR-450b-5p', 'hsa-miR-4510', 'hsa-miR-4511', 'hsa-miR-4512', 'hsa-miR-4513', 'hsa-miR-4514', 'hsa-miR-4515

    Sample      GSM_ID       Tissue  Patient_ID  LH_Day Condition
0    13586  GSM2916723  endometrium           8       2   CONTROL
1    13590  GSM2916724  endometrium           8       8   CONTROL
2    13606  GSM2916725        blood           8       2   CONTROL
3    13610  GSM2916726        blood           8       8   CONTROL
4    13879  GSM2916727  endometrium          11       2   CONTROL
..     ...         ...          ...         ...     ...       ...
86  141270  GSM2916809        blood          25       8       IVF
87  141271  GSM2916810        blood          26       8       IVF
88  141272  GSM2916811        blood          27       8       IVF
89  141273  GSM2916812        blood          28       8       IVF
90  141299  GSM2916813  endometrium          33       8       IVF

[91 rows x 6 columns]

In [12]:
model_data_est = pd.read_csv(r"F:\downloads microsodt\GSE108966_EST_RIF_ml_dataset.csv") 
display(model_data_est.head(3))
print(model_data_est.shape)

print(model_data_est['Condition'].value_counts())
print(model_data_est['Tissue'].value_counts())

,Sample,GSM_ID,Tissue,Patient_ID,LH_Day,Condition,hsa-let-7a-3p,hsa-let-7a-5p,hsa-let-7a-2-3p,hsa-let-7b-5p,...,hsa-miR-95-5p,hsa-miR-95-3p,hsa-miR-96-5p,hsa-miR-96-3p,hsa-miR-98-3p,hsa-miR-98-5p,hsa-miR-99a-3p,hsa-miR-99a-5p,hsa-miR-99b-5p,hsa-miR-99b-3p
0,ERTK11LH2E,GSM2916612,endometrium,ERTK11,2,CONTROL,375,210095,0,10134,...,6,30,782,0,33,15744,118,4998,16907,51
1,ERTK11LH8E,GSM2916613,endometrium,ERTK11,8,CONTROL,1091,279622,2,25660,...,12,85,1345,1,176,14554,309,7993,21134,274
2,NOT1209LH2B,GSM2916614,blood,NOT1209,2,CONTROL,2,12090,0,1899,...,0,0,147,0,0,270,0,42,1011,0

(111, 2594)
Condition
CONTROL    80
IVF        31
Name: count, dtype: int64
Tissue
endometrium    64
blood          47
Name: count, dtype: int64

In [14]:
[x for x in model_data_est.columns if "3607" in str(x)]

['hsa-miR-3607-3p', 'hsa-miR-3607-5p']